#!/bin/sh

obj="$1"
exitcode="$2"

dep="`echo "$obj" | sed -e 's:\.o$:.d:' -e 's:\.gch$:.d:'`"
test -f "$dep" || exit $exitcode

test -f .deps && rm -f .deps
test -d .deps || mkdir .deps 2> /dev/null
if test ! -d .deps; then
  rm -f "$dep"
  exit 1
fi

target="`echo "$dep" | sed -e 's:/:_:g'`"
mv "$dep" ".deps/$target" || rm -f "$dep"

exit $exitcode
