'\" t
.\"     Title: mkvextract
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 2011-12-18
.\"    Manual: Користувацькі команди
.\"    Source: MKVToolNix 5.2.0
.\"  Language: Ukrainian
.\"
.TH "mkvextract" "1" "2011\-12\-18" "MKVToolNix 5\&.2\&.0" "Користувацькі команди"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
mkvextract \- витягнення доріжок з файлів Matroska(TM) до інших файлів
.SH "КОРОТКИЙ ОПИС"
.HP \w'\fBmkvextract\fR\ 'u
\fBmkvextract\fR {mode} {source\-filename} [options] [extraction\-spec]
.SH "ОПИС"
.PP
Даний додаток витягує означені частини файла
Matroska(TM)
до файлів інших форматів\&. За допомогою першого аргументу,
\fBmode\fR,
\fBmkvextract\fR(1)
інформується про те, що треба витягати\&. Наразі підтримується витягнення
tracks,
tags,
attachments,
chapters,
CUE sheets
and
timecodes\&. Другий аргумент виступає повною назвою вхідного файла\&. Це має бути файл
Matroska(TM)\&. Всі зазначені аргументи є опціями і спицифікаціями для витягнення і залежать від вибраного режиму\&.
.SS "Загальні опції"
.PP
Нижчевказані опції доступні у всіх режимах і тому лише раз описуються в данному розділі\&.
.PP
\fB\-f\fR, \fB\-\-parse\-fully\fR
.RS 4
Встановлює режим аналізу як \*(Aqfull\*(Aq\&. За допомогою типового режиму не аналізується увесь файл, а використовуються елементи метапошуку для виявлення необхідних елементів вхідного файла\&. В 99% випадків цього достатньо\&. Але для аналізу файлів, що не містять елементів метапошуку або є пошкодженими треба використовувати цей режим\&. Повне сканування файлу може тривати кілька хвилин, в той час як швидке \- кілька секунд\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fIcharacter\-set\fR
.RS 4
Встановлює набір символів заданого в командному рядку для конвертації\&. Типово використовується набір символів згідно поточної локалі системи\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIcharacter\-set\fR
.RS 4
Встановлює вихідний набір символів заданого в командному рядку для конвертації\&. Типово використовується набір символів згідно поточної локалі системи\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fIfile\-name\fR
.RS 4
Всі повідомлення записуються до файлу
\fIfile\-name\fR
замість консолі\&. Хоча це можна зробити через перенаправлення виводу, є деякі випадки, коли необхідно застосовувати саме дану опцію: коли термінал інтерпретує в інший спосіб вивід перед записом до файлу\&. Набір символів, заданий через
\fB\-\-output\-charset\fR
враховується\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIcode\fR
.RS 4
Задає примусове використання мовного перекладу
\fIcode\fR
інтерфейсу (наприклад, \*(Aqde_DE\*(Aq для німецького перекладу)\&. Тому, краще використовувати змінні середовища
\fILANG\fR,
\fILC_MESSAGES\fR
і
\fILC_ALL\fR\&. Після введення
list\*(Aq як
\fIcode\fR
\fBmkvextract\fR(1)
відобразить список доступних перекладів\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Задає відображення розширеної інформації про важливі елементи
Matroska(TM)\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Відображається інформація про використання додатку і відбувається завершення роботи додатку\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Відображається інформація про версію додатку і відбувається завершення роботи додатку\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Відбувається перевірка на наявність нової версії шляхом завантаження з URL
http://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\&. Буде відображено чотири рядка у
key=value
стилі: URL, звідки отримана інформація (key
version_check_url), поточна запущена версія (key
running_version), остання випущена версія (key
available_version) і URL для завантаження (key
download_url)\&.
.sp
Після чого додаток завершує роботу з кодом повернення 0, якщо немає нової версії, і з кодом 2, якщо виникла помилка (наприклад, коли не було отримано інформації про оновлення взагалі)\&.
.sp
Дана опція наявна лише тоді, коли додаток компілювався з підтримкою libcurl\&.
.RE
.PP
\fB@\fR\fIoptions\-file\fR
.RS 4
Зчитує додаткові параметри командного рядка з файла
\fIoptions\-file\fR\&. Рядки, які містять зразу після символу переносу рядка мітку хеша (\*(Aq#\*(Aq) сприймаються як коментарі і ігноруються\&. Символи переносу на початку і в кінці рядка опускаються\&. Кожний рядок має містити лише один параметр\&.
.sp
Дозволяється використовувати спеціальні символи при умові їх виокремлення, наприклад, якщо треба розпочати рядок (не коментар) з \*(Aq#\*(Aq\&. Правила описані в
the section about escaping text\&.
.sp
Командний рядок \*(Aq\fBmkvextract tracks source\&.mkv \-\-raw 1:destination\&.raw\fR\*(Aq може бути перетворений на наступний конфігураційний файл:
.sp
.if n \{\
.RS 4
.\}
.nf
# Extract a track from source\&.mkv
tracks
source\&.mkv
# Output the track as raw data\&.
\-\-raw
1:destination\&.raw
.fi
.if n \{\
.RE
.\}
.RE
.SS "Режим витягнення доріжок"
.PP
Синтаксис:
\fBmkvextract\fR
\fBtracks\fR
\fIsource\-filename\fR
[\fIoptions\fR]
\fITID1:dest\-filename1\fR
[\fITID2:dest\-filename2\fR \&.\&.\&.]
.PP
Наступні опції командного рядка доступні для кожної доріжки в режимі витягнення \*(Aqtracks\*(Aq\&. Вони мають бути присутні після вказання доріжки (див\&. нижче), до якої будуть застосовуватись\&.
.PP
\fB\-c\fR \fIcharacter\-set\fR
.RS 4
Задається набір символів, який має містити наступна доріжка субтитрів після конвертації\&. Застосовується лише тоді, коли ID наступної доріжки вказує на доріжку субтитрів\&. Типовим набором символів є UTF\-8\&.
.RE
.PP
\fB\-\-blockadd\fR \fIlevel\fR
.RS 4
Залишати лише BlockAdditions до цього рівня\&. Типово враховуються усі рівні\&. Дана опція може нашкодити лише деяким кодекам, як то WAVPACK4\&.
.RE
.PP
\fB\-\-cuesheet\fR
.RS 4
Відбувається витягнення
\fBmkvextract\fR(1)
списків
CUE
з інформацією про розділи і дані тегів даної доріжки до файлу з назвою, що відповідає такій для вихідної назви доріжки з розширенням \*(Aq\&.cue\*(Aq\&.
.RE
.PP
\fB\-\-raw\fR
.RS 4
Відбувається витягнення "сирих" даних до файлу без контейнера\&. На відміну від прапорця
\fB\-\-fullraw\fR
даний параметр не призводить до запису складових елементу
CodecPrivate
до файлу\&. Даний режим може працювати з усіма
CodecIDs, навіть з тими, які
\fBmkvextract\fR(1)
не підтримує, але це може призвести до створення пошкодженого файлу\&.
.RE
.PP
\fB\-\-fullraw\fR
.RS 4
Відбувається витягнення "сирих" даних до файлу без контейнера\&. Складові елементу
CodecPrivate
будуть записуватися до файлу спочатку, якщо доріжка містить такий елемент заголовку\&. Даний режим може працювати з усіма
CodecIDs, навіть з тими, які
\fBmkvextract\fR(1)
не підтримує, але це може призвести до створення пошкодженого файлу\&.
.RE
.PP
\fITID:outname\fR
.RS 4
Відбувається витягнення доріжки з ID
\fITID\fR
до файлу
\fIoutname\fR
за умови, якщо така доріжка міститься у вхідному файлі\&. Дану опцію можна задавати декілька разів\&. ID доріжок мають бути такі самі як і при виведенні інформації командою
\fBmkvmerge\fR(1)
з параметром
\fB\-\-identify\fR\&.
.sp
Кожна назва вихідного файлу має використовуватися лише раз\&. Виняток становлять доріжки RealAudio і RealVideo\&. Якщо використовувати однакові назви для різних доріжок, то вони будуть збережені до одного й того самого файлу\&. Наприклад:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tracks input\&.mkv 1:output\-two\-tracks\&.rm 2:output\-two\-tracks\&.rm
.fi
.if n \{\
.RE
.\}
.RE
.SS "Режим витягнення тегів"
.PP
Синтаксис:
\fBmkvextract\fR
\fBtags\fR
\fIsource\-filename\fR
[\fIoptions\fR]
.PP
Витягнуті теги записуються до консолі, якщо інформація на виході не перенаправляється (щоб розібратися детально, див\&. розділ
output redirection)\&.
.SS "Режим витягнення вкладень"
.PP
Синтаксис:
\fBmkvextract\fR
\fBattachments\fR
\fIsource\-filename\fR
[\fIoptions\fR]
\fIAID1:outname1\fR
[\fIAID2:outname2\fR \&.\&.\&.]
.PP
\fIAID\fR:\fIoutname\fR
.RS 4
Відбувається витягнення вкладення з ID
\fIAID\fR
до файлу
\fIoutname\fR
за умови, якщо таке вкладення міститься у вхідному файлі\&. Якщо ж залишити
\fIoutname\fR
пустим, то буде використовуватися назва вкладення з вхідного файла
Matroska(TM)\&. Дану опцію можна задавати декілька разів\&. ID вкладень мають бути такі самі як і при виведенні інформації командою
\fBmkvmerge\fR(1)
з параметром
\fB\-\-identify\fR\&.
.RE
.SS "Режим витягнення розділів"
.PP
Синтаксис:
\fBmkvextract\fR
\fBchapters\fR
\fIsource\-filename\fR
[\fIoptions\fR]
.PP
\fB\-s\fR, \fB\-\-simple\fR
.RS 4
Витягується інформація про розділи у простому форматі, що використовується в інструментарії для роботи з
OGM
(CHAPTER01=\&.\&.\&., CHAPTER01NAME=\&.\&.\&.)\&. В цьому режимі деяка інформація пропускається\&. Типово, розділи витягуються у форматі
XML\&.
.RE
.PP
Витягнуті розділи записуються до консолі, якщо інформація на виході не перенаправляється (щоб розібратися детально, див\&. розділ
output redirection)\&.\&.
.SS "Режим витягнення списків Cue"
.PP
Синтаксис:
\fBmkvextract\fR
\fBcuesheet\fR
\fIsource\-filename\fR
[\fIoptions\fR]
.PP
Витягнуті списки Cue записуються до консолі, якщо інформація на виході не перенаправляється (щоб розібратися детально, див\&. розділ
output redirection)\&.
.SS "Режим витягнення тайм\-кодів"
.PP
Синтаксис:
\fBmkvextract\fR
\fBtimecodes_v2\fR
\fIsource\-filename\fR
[\fIoptions\fR]
\fITID1:dest\-filename1\fR
[\fITID2:dest\-filename2\fR \&.\&.\&.]
.PP
Витягнуті тайм\-коди записуються до консолі, якщо інформація на виході не перенаправляється (щоб розібратися детально, див\&. розділ
output redirection)\&.
.PP
\fITID:outname\fR
.RS 4
Відбувається витягнення тайм\-кодів доріжок з ID
\fITID\fR
до файлу
\fIoutname\fR
за умови, якщо така доріжка міститься у вхідному файлі\&. Дану опцію можна задавати декілька разів\&. ID доріжок мають бути такі самі як і при виведенні інформації командою
\fBmkvmerge\fR(1)
з параметром
\fB\-\-identify\fR\&.
.sp
Наприклад:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract timecodes_v2 input\&.mkv 1:tc\-track1\&.txt 2:tc\-track2\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SH "ПЕРЕНАПРАВЛЕННЯ ВИХІДНИХ ДАНИХ"
.PP
Деякі режими витягнення змушують
\fBmkvextract\fR(1)
записувати дані, що витягуються, до консолі\&. Існує два способи запису цих даних до файлу: за допомогою командної оболонки або використовуючи саме
\fBmkvextract\fR(1)\&.
.PP
Для використання перенаправлення за допомогою командної оболонки треба додати \*(Aq> output\-filename\&.ext\*(Aq до командного рядка\&. Наприклад:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tags source\&.mkv > tags\&.xml
.fi
.if n \{\
.RE
.\}
.PP
Перенаправлення за допомогою
\fBmkvextract\fR(1)
здійснюється через опцію
\fB\-\-redirect\-output\fR\&. Наприклад:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tags source\&.mkv \-\-redirect\-output tags\&.xml
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBПримітка\fR
.ps -1
.br
.PP
Якщо вашою ОС є Windows, то вам краще використовувати саме опцію
\fB\-\-redirect\-output\fR, так як
\fBcmd\&.exe\fR
деколи інтерпретує спеціальні символи перед записом їх до файлу на виході, що може призвести до його пошкодження\&.
.sp .5v
.RE
.SH "ФОРМАТИ ФАЙЛІВ НА ВИХОДІ"
.PP
Рішення щодо формату файлу на виході обирається, базуючись на типі доріжки, а не на типі файлу, що буде записаний\&. У даний час підтримуються наступні типи доріжок:
.PP
V_MPEG4/ISO/AVC
.RS 4

H\&.264
/
AVC
доріжки відео записуються до
H\&.264
елементарних потоків, які можуть надалі бути оброблені за допомогою, наприклад,
MP4Box(TM)
зі збірки
GPAC(TM)\&.
.RE
.PP
V_MS/VFW/FOURCC
.RS 4
Доріжки відео з виправленим
FPS
з таким
CodecID
записуються до файлів
AVI\&.
.RE
.PP
V_REAL/*
.RS 4
Доріжки
RealVideo(TM)
записуються до файлів
RealMedia(TM)\&.
.RE
.PP
A_MPEG/L3, A_AC3
.RS 4
Дані доріжки будуть витягнуті до необроблених файлів
MP3
і
AC3\&.
.RE
.PP
A_PCM/INT/LIT
.RS 4
Необроблені
PCM
дані будуть записані до файлу
WAV\&.
.RE
.PP
A_AAC/MPEG2/*, A_AAC/MPEG4/*, A_AAC
.RS 4
Усі файли
AAC
будуть записані до файлів
AAC
з заголовками
ADTS
перед кожним пакетом\&. Заголовки
ADTS
не будуть містити застарілого поля особливого призначення\&.
.RE
.PP
A_VORBIS
.RS 4
Файли аудіо Vorbis будуть записані до файлу
OggVorbis(TM)\&.
.RE
.PP
A_REAL/*
.RS 4
Доріжки
RealAudio(TM)
записуються до файлів
RealMedia(TM)\&.
.RE
.PP
A_TTA1
.RS 4
ДоріжкиTrueAudio(TM)
записуються до файлів
TTA\&. Майте на увазі, що через обмежену точність тайм\-кодів
Matroska(TM), витягнуті заголовки файлів будуть різними, що зазначено у двох полях:
\fIdata_length\fR
(сумарна кількість семплів у файлі) і
CRC\&.
.RE
.PP
S_TEXT/UTF8
.RS 4
Прості текстові субтитри будуть записані до файлів
SRT\&.
.RE
.PP
S_TEXT/SSA, S_TEXT/ASS
.RS 4
Текстові субтитри
SSA
і
ASS
будуть записані до файлів
SSA/ASS
відповідно\&.
.RE
.PP
S_KATE
.RS 4
Потоки
Kate(TM)
будуть записані до контейнеру
Ogg(TM)\&.
.RE
.PP
Теги
.RS 4
Теги конвертуються до формату
XML\&. Цей формат є тим самим, який
\fBmkvmerge\fR(1)
підтримує для читання тегів\&.
.RE
.PP
Вкладення
.RS 4
Вкладення записуються як є до файлу на виході\&. Ніяких перетворень не виконується\&.
.RE
.PP
Розділи
.RS 4
Розділи конвертуються до формату
XML\&. Цей формат є тим самим, який
\fBmkvmerge\fR(1)
підтримує для читання розділів\&. Як альтернатива, можна витягувати розділи до спрощеного стильового формату
OGM\&.
.RE
.PP
Тайм\-коди
.RS 4
Тайм\-коди спочатку сортуються і потім виводяться у сумісному файловому форматі тайм\-кодів v2 для використання
\fBmkvmerge\fR(1)\&. Витягнення до інших форматів (v1, v3 і v4) не підтримується\&.
.RE
.SH "КОДИ ЗАВЕРШЕННЯ"
.PP

\fBmkvextract\fR(1)
завершує роботу одним з трьох кодів завершення:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB0\fR
\-\- Цей код означає, що витягнення пройшло успішно\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB1\fR
\-\- В цьому випадку
\fBmkvextract\fR(1)
було видано хоча б одне попередження, проте витягнення продовжувалось\&. Попередженню передує текст \*(AqWarning:\*(Aq\&. В залежності від помилок, що сталися, результуючі файли можуть бути або цілими, або пошкодженими\&. Користувачу рекомендується як звернути увагу на саме попередження, так і перевірити результуючі файли\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB2\fR
\-\- Цей код завершення використовується у випадку помилки\&.
\fBmkvextract\fR(1)
припиняє роботу одразу після виведення повідомлення про помилку\&. Помилки виникають через невірні параметри командного рядка, помилки читання/запису або через з самого початку пошкоджені файли\&.
.RE
.SH "ВИОКРЕМЛЕННЯ СПЕЦІАЛЬНИХ СИМВОЛІВ У ТЕКСТІ"
.PP
Є декілька місць, де спеціальні символи у тексті мають або повинні бути виокремлені\&. Правила для виокремлювання прості: кожен символ, що потребує виокремлення, замінюється на зворотній слеш з деяким символом, що йде після нього\&.
.PP
The rules are: \*(Aq \*(Aq (a space) becomes \*(Aq\es\*(Aq, \*(Aq"\*(Aq (double quotes) becomes \*(Aq\e2\*(Aq, \*(Aq:\*(Aq becomes \*(Aq\ec\*(Aq, \*(Aq#\*(Aq becomes \*(Aq\eh\*(Aq and \*(Aq\e\*(Aq (a single backslash) itself becomes \*(Aq\e\e\*(Aq\&.
.SH "ДИВІТЬСЯ ТАКОЖ"
.PP

\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1),
\fBmmg\fR(1)
.SH "WWW"
.PP
Остання версія завжди може бути знайдена на веб\-сторінці
\m[blue]\fBthe MKVToolNix homepage\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "Author"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Розробник
.RE
.SH "ПРИМІТКИ"
.IP " 1." 4
the MKVToolNix homepage
.RS 4
\%http://www.bunkus.org/videotools/mkvtoolnix/
.RE
