'\" t
.\"     Title: mkvpropedit
.\"    Author: Bunkus Moritz[FAMILY Given] <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 2011-01-31
.\"    Manual:  
.\"    Source: MkvToolNix 4.5.0
.\"  Language: Japanese
.\"
.TH "MKVPROPEDIT" "1" "2011\-01\-31" "MkvToolNix 4\&.5\&.0" ""
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
mkvpropedit \- 再MUXすることなく、既存のMatroska(TM)ファイルのプロパティを修正する
.SH "書式"
.HP \w'\fBmkvpropedit\fR\ 'u
\fBmkvpropedit\fR [options] {source\-filename}
.SH "説明"
.PP
このプログラムは、既存のMatroska(TM)ファイルを解析し、そのプロパティのいくつかを修正します。そして、それらの修正を既存のファイルに書き込みます。プロパティの中で変更可能なのは、セグメント情報エレメント(例えばタイトル)と、トラックヘッダ(例えば言語コードや\*(Aqデフォルトトラック\*(Aqフラグ、トラック名)です。
.PP
オプション:
.PP
\fB\-l\fR, \fB\-\-list\-property\-names\fR
.RS 4
既知の編集可能なプロパティの名前、型(文字列、整数、真偽値等)、短い説明を一覧表示します。その後、プログラムは終了します。よって、\fIsource\-filename\fRパラメータを指定する必要はありません。
.RE
.PP
\fB\-p\fR, \fB\-\-parse\-mode\fR \fImode\fR
.RS 4
解析モードを設定します。\*(Aq\fImode\fR\*(Aqパラメータは\*(Aqfast\*(Aq(デフォルト)と\*(Aqfull\*(Aqのどちらかを指定できます。\*(Aqfast\*(Aqモードはファイル全体を解析するのではなく、メタシークエレメントを使ってソースファイル内の必要なエレメントを探します。99%の場合これで十分です。しかし、メタシークエレメントを含まないファイルや破損したファイルに対しては\*(Aqfull\*(Aq解析モードを指定する必要があるかもしれません。\*(Aqfull\*(Aqスキャンには数分かかることがありますが、\*(Aqfast\*(Aqスキャンには数秒しかかかりません。
.RE
.PP
アクション:
.PP
\fB\-e\fR, \fB\-\-edit\fR \fIselector\fR
.RS 4
このオプション以降のadd、set、deleteアクションが適用されるMatroska(TM)ファイルセクション(セグメント情報または特定のトラックのヘッダ)を指定します。このオプションは、複数のエレメントを修正するために、複数回指定することができます。
.sp
デフォルトでは、\fBmkvpropedit\fR(1)はセグメント情報のセクションを編集します。
.sp
文法の完全な説明は、エディットセレクタのセクションを参照してください。
.RE
.PP
\fB\-a\fR, \fB\-\-add\fR \fIname\fR=\fIvalue\fR
.RS 4

\fIname\fRで指定された名前のプロパティを\fIvalue\fRで指定した値で追加します。プロパティは、既にその名前のプロパティが存在する場合も追加されます。ほとんどのプロパティは一意的で、複数回追加できないことに注意してください。
.RE
.PP
\fB\-s\fR, \fB\-\-set\fR \fIname\fR=\fIvalue\fR
.RS 4
見付けた全ての、プロパティ名が\fIname\fRであるプロパティの値を、\fIvalue\fRに設定します。そのようなプロパティが存在しないときは、プロパティは追加されます。
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR \fIname\fR
.RS 4
見付けた全ての、プロパティ名が\fIname\fRであるプロパティを削除します。いくつかのプロパティは必須で、削除できないことに注意してください。
.RE
.PP
その他のオプション:
.PP
\fB\-\-command\-line\-charset\fR \fIcharacter\-set\fR
.RS 4
コマンドライン文字列の文字コードを指定します。デフォルトは、システムの現在のロケールの文字コードになります。
.RE
.PP
\fB\-\-output\-charset\fR \fIcharacter\-set\fR
.RS 4
出力する文字コードを指定します。デフォルトは、システムの現在のロケールの文字コードになります。
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fIfile\-name\fR
.RS 4
全てのメッセージをコンソールではなく\fIfile\-name\fRで指定したファイルに書き出します。出力リダイレクトによっても同じことが簡単にできますが、このオプションが必要な場合もあります。ターミナルがファイルに書き込む前に出力を処理してしまう場合などです。\fB\-\-output\-charset\fRによって指定された文字コードは尊重されます。
.RE
.PP
\fB\-\-ui\-language\fR \fIcode\fR
.RS 4
指定した\fIcode\fRを強制的に言語コード(例: 日本語ならば\*(Aqja_JP\*(Aq)として使用します。しかし、環境変数\fILANG\fRや\fILC_MESSAGES\fR、\fILC_ALL\fRを使用したほうが好ましいでしょう。\fIcode\fRにlistと指定すると、指定できる言語コードの一覧を出力します。
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
出力が冗長になり、Matroska(TM)のエレメントにとって重要なこと全てを、読み込まれるつどに表示していきます。
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
コマンド書式情報を出力して終了します。
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
バージョン情報を出力して終了します。
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4

http://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xmlをダウンロードすることで、新しいリリースがないかオンラインでチェックします。key=valueという書式で、4行が出力されます：どこから情報を取得したか (key
version_check_url)、現在実行中のバージョン (key
running_version)、最新のリリースのバージョン (key
available_version) 及びそのダウンロードURL (key
download_url)。
.sp
その後プログラムは、新しいリリースが入手可能ではなかった場合は終了コード0で、新しいリリースが入手可能であった場合は終了コード1で、エラーが発生した場合（例：アップデート情報を取得できなかった場合）は終了コード2で、それぞれ終了します。
.sp
このオプションは、プログラムがlibcurlのサポートつきでビルドされた場合のみ使用できます。
.RE
.PP
\fB@\fRoptions\-file
.RS 4

\fIoptions\-file\fRで指定されたファイルから追加のコマンドラインオプションを読み込みます。行で最初の空白文字でない文字がハッシュマーク(\*(Aq#\*(Aq)である行はコメントとして扱われ、無視されます。行頭、及び行末の空白文字は取り除かれます。各行には一つずつしかオプションを指定できません。
.sp
エスケープすることのできる文字もあります。例えば、コメントではない行を\*(Aq#\*(Aqで始める必要のある場合です。そのルールは、エスケープ文字についてのセクションで説明されています。
.sp
\*(Aq\fBmkvpropedit source\&.mkv \-\-edit trach:a2 \-\-set name=Comments\fR\*(Aqというコマンドラインと同じことは、次のようなオプションファイルによって指定できます。
.sp
.if n \{\
.RS 4
.\}
.nf
# Modify source\&.mkv
source\&.mkv
# Edit the second audio track
\-\-edit
track:a2
# and set the title to \*(AqComments\*(Aq
\-\-set
title=Comments
     
.fi
.if n \{\
.RE
.\}
.RE
.SH "エディットセレクタ"
.PP

\fB\-\-edit\fRオプションは、以降のadd、set及びdeleteアクションが適用されるMatroska(TM)ファイルセクション(セグメント情報または特定のトラックヘッダ)を設定します。これは次の\fB\-\-edit\fRオプションが見付かるまでずっと有効です。このオプションへの引数はエディットセレクタと呼ばれます。
.PP
デフォルトでは、\fBmkvpropedit\fR(1)はセグメント情報のセクションを編集します。
.SS "セグメント情報"
.PP
セグメント情報は次の3つの単語によって選択されます。\*(Aqinfo\*(Aq、\*(Aqsegment_info\*(Aqまたは\*(Aqsegmentinfo\*(Aqです。これはセグメントタイトルやセグメントUIDなどのプロパティを格納しています。
.SS "トラックヘッダ"
.PP
トラックヘッダはもうちょっとだけ複雑なセレクタで選択されます。全ての場合でセレクタは\*(Aqtrack:\*(Aqで始まります。トラックヘッダプロパティには、言語コード、\*(Aqデフォルトトラック\*(Aqフラグやトラック名のようなエレメントがあります。
.PP
\fBtrack:\fR\fIn\fR
.RS 4
パラメータ\fIn\fRが数字であれば、\fIn\fR番目のトラックが選択されます。トラックの順番は、\fBmkvmerge\fR(1)に\fB\-\-identify\fRオプションを指定すると出力されるものと同じです。
.RE
.PP
\fBtrack:\fR\fIt\fR\fIn\fR
.RS 4
パラメータが一文字の英字\fIt\fRで始まり、次に\fIn\fRが続く場合、あるトラックタイプで\fIn\fR番目のトラックが選択されます。トラックタイプパラメータ\fIt\fRは、オーディオトラックを示す\*(Aqa\*(Aq、ボタントラックを示す\*(Aqb\*(Aq、字幕トラックを示す\*(Aqs\*(Aq、ビデオトラックを示す\*(Aqv\*(Aqの四つのうちの一つでなければなりません。トラックの順番は\fBmkvmerge\fR(1)の\fB\-\-identify\fRオプションで出力される順番と同じです。
.RE
.PP
\fBtrack:\fR=\fIuid\fR
.RS 4
パラメータが\*(Aq=\*(Aqで始まり、次に\fIuid\fRが続く場合は、トラックUIDエレメントが\fIuid\fRのトラックが選択されます。トラックUIDは\fBmkvinfo\fR(1)で取得できます。
.RE
.PP
\fBtrack:\fR@\fInumber\fR
.RS 4
パラメータが\*(Aq@\*(Aqで始まり、次に\fInumber\fRが続く場合は、トラックナンバーエレメントが\fInumber\fRと等しいトラックが選択されます。トラックナンバーは\fBmkvinfo\fR(1)で取得できます。
.RE
.SS "注意"
.PP
トラックエディットセレクタの性質から、いくつかのセレクタが同じトラックヘッダにマッチすることがあります。このような場合、それらのエディットセレクタへの全てのアクションは一つにまとめられ、コマンドラインに指定された順番に実行されます。
.SH "例"
.PP
下に\*(Aqmovie\&.mkv\*(Aqというファイルを編集する例を示します。この例では、セグメントタイトルを設定し、オーディオトラックと字幕トラックの言語コードを修正します。この例は、最初の\fB\-\-edit\fRオプションが見付かる前の全てのオプションはデフォルトで結局セグメント情報エレメントを編集するので、最初の\fB\-\-edit\fRオプションを省略して短縮できることに注意してください。
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit movie\&.mkv \-\-edit info \-\-set "title=The movie" \-\-edit track:a1 \-\-set language=fre \-\-edit track:a2 \-\-set language=ita
  
.fi
.if n \{\
.RE
.\}
.PP
二番目の例は、最初の字幕トラックから\*(Aqデフォルトトラックフラグ\*(Aqを削除し二番目の字幕トラックに設定します。\fBmkvpropedit\fR(1)は\fBmkvmerge\fR(1)とは違い、\*(Aqデフォルトトラックフラグ\*(Aqが違うトラックで\*(Aq1\*(Aqに設定されているからといって自動的に他のトラックの\*(Aqデフォルトトラックフラグ\*(Aqを\*(Aq0\*(Aqに設定はしない、という点に注意してください。
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit movie\&.mkv \-\-edit track:s1 \-\-set flag\-default=0 \-\-edit track:s2 \-\-set flag\-default=1
  
.fi
.if n \{\
.RE
.\}
.SH "返り値"
.PP

\fBmkvpropedit\fR(1)は下の3つの返り値を返します。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB0\fR
\-\- この返り値は変更が成功したことを示します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB1\fR
\-\- この返り値は、一つ以上の警告が出力されましたが、抽出が続行されたことを意味します。警告は \*(Aq警告:\*(Aq という文字列を先頭につけて出力されます。出力ファイルが無事であるかどうかは、場合によります。出力ファイルを確認することを強く推奨します。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
この返り値は、エラーが発生し、エラーメッセージを表示した直後に\fBmkvpropedit\fR(1)が終了したことを示します。エラーメッセージは不正なコマンドラインやファイルI/Oエラー、壊れたファイルなど様々です。
.RE
.SH "テキスト中の特殊文字をエスケープする"
.PP
特殊文字をエスケープしなければならない、あるいはすべき場所が少しだけあります。エスケープのルールは単純です：エスケープする必要のある各文字を、バックスラッシュ（日本語フォントでは\e記号）の後ろに違う文字が1つついたものと入れ替えます。
.PP
ルール：\*(Aq \*(Aqは\*(Aq\es\*(Aqに、\*(Aq"\*(Aqは\*(Aq\e2\*(Aqに、\*(Aq:\*(Aqは\*(Aq\ec\*(Aqに、\*(Aq#\*(Aqは\*(Aq\eh\*(Aqに、そして\*(Aq\e\*(Aqそれ自体は\*(Aq\e\e\*(Aqになります。
.SH "関連項目"
.PP

\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvextract\fR(1),
\fBmmg\fR(1)
.SH "ウェブ"
.PP
最新のバージョンは、常時\m[blue]\fBMKVToolNixのホームページ\fR\m[]\&\s-2\u[1]\d\s+2から取得できます。
.SH "著者"
.PP
\fBBunkus Moritz[FAMILY Given]\fR <\&moritz@bunkus\&.org\&>
.RS 4
開発者
.RE
.SH "注記"
.IP " 1." 4
MKVToolNixのホームページ
.RS 4
\%http://www.bunkus.org/videotools/mkvtoolnix/
.RE
