'\" t
.\"     Title: mmg
.\"    Author: Bunkus Moritz[FAMILY Given] <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2013-09-16
.\"    Manual:  
.\"    Source: MKVToolNix 6.4.1
.\"  Language: Japanese
.\"
.TH "MMG" "1" "2013\-09\-16" "MKVToolNix 6\&.4\&.1" ""
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
mmg \- \fBmkvmerge\fR(1) のチャプタ、ヘッダ編集機能付きGUI
.SH "書式"
.HP \w'\fBmmg\fR\ 'u
\fBmmg\fR [[\-\-edit\-headers\ {filename\&.mkv}] | [preferences\-file\&.mmg] | [source\-file\&.ext]]
.SH "説明"
.PP
\fBmmg\fR(1)は、wxWindows(TM)ベースの\fBmkvmerge\fR(1)のGUIです。\fBmkvmerge\fR(1)の全てのオプションを簡単に使用できます。全ての設定(例：ソースファイル、トラックオプションなど)は保存・読み込みが可能です。Matroska(TM)ファイルからチャプタ情報を読みこむことができ、またOGM形式、XML形式のチャプタファイルを読み込み可能で、XML形式に書き出し可能なチャプタエディタが搭載されています。さらに、既存のMatroska(TM)ファイルのヘッダを再MUXすることなく書き換え可能なヘッダエディタも搭載されています。
.PP
\fBmmg\fR(1)はあまり多くのオプションをとりません。最初に考えられるのは、一つのファイル名を指定することです。もし、ファイル名の拡張が\*(Aq\&.mmg\*(Aqであれば、そのファイルは設定ファイルとして扱われ、\fBmmg\fR(1)はスタート時に設定を読み込みます。もしそうでなければ、ファイル名は入力ファイルとして追加されるファイルの名前として扱われます。
.PP
二番目の動作モードに入るには、\fB\-\-edit\-headers\fRオプションをファイル名と共に指定します。すると、\fBmmg\fR(1)はヘッダエディタを立ち上げ、ファイルを読み込みます。
.PP
完全なドキュメントは、HTML形式で存在します。(doc/mkvmerge\-gui\&.html)
.SH "関連項目"
.PP
\fBmkvmerge\fR(1)\fBmkvextract\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1)
.SH "ウェブ"
.PP
最新のバージョンは、常時\m[blue]\fBMKVToolNixのホームページ\fR\m[]\&\s-2\u[1]\d\s+2から取得できます。
.SH "著者"
.PP
\fBBunkus Moritz[FAMILY Given]\fR <\&moritz@bunkus\&.org\&>
.RS 4
開発者
.RE
.SH "注記"
.IP " 1." 4
MKVToolNixのホームページ
.RS 4
\%http://www.bunkus.org/videotools/mkvtoolnix/
.RE
