'\" t
.\"     Title: mkvinfo
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.78.0 <http://docbook.sf.net/>
.\"      Date: 2013-02-26
.\"    Manual: 用户命令
.\"    Source: MKVToolNix 6.1.0
.\"  Language: Chinese
.\"
.TH "MKVINFO" "1" "2013\-02\-26" "MKVToolNix 6\&.1\&.0" "用户命令"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名称"
mkvinfo \- 输出关于 Matroska(TM) 文件中各轨的信息
.SH "概要"
.HP \w'\fBmkvinfo\fR\ 'u
\fBmkvinfo\fR [选项] {源文件名}
.SH "说明"
.PP
本程序可列出
Matroska(TM)文件中包含的所有轨道，输出信息可以限定为文件的轨道列表以及所用编解码器的信息。
.PP
\fB\-g\fR, \fB\-\-gui\fR
.RS 4
启动
GUI。本选项仅当 mkvinfo 编译时附加
GUI
支持时可用。
.RE
.PP
\fB\-c\fR, \fB\-\-checksums\fR
.RS 4
计算并显示各帧的
\fBAdler32\fR
校验码。仅当调试时有用处。
.RE
.PP
\fB\-s\fR, \fB\-\-summary\fR
.RS 4
仅显示
\fBmkvinfo\fR(1)
所获取信息的简要概述，而非各元素。
.RE
.PP
\fB\-t\fR, \fB\-\-track\-info\fR
.RS 4
在\(lq详细\(rq模式下为各轨道显示统计信息。如果\(lq详细\(rq程度为 0 级，则将同时将级别设为 1。
.RE
.PP
\fB\-x\fR, \fB\-\-hexdump\fR
.RS 4
以十六进制转储形式显示各帧的前 16 字节。
.RE
.PP
\fB\-X\fR, \fB\-\-full\-hexdump\fR
.RS 4
以十六进制转储形式显示各帧的所有字节。
.RE
.PP
\fB\-z\fR, \fB\-\-size\fR
.RS 4
显示各元素的尺寸，含头部所占用的尺寸。
.RE
.PP
\fB\-\-command\-line\-charset\fR \fI字符集\fR
.RS 4
设定在命令行给出的字符串的字符集，用于转为其他字符集。默认为系统当前区域设置中所给定的字符集。
.RE
.PP
\fB\-\-output\-charset\fR \fI字符集\fR
.RS 4
设置输出的字符串应被转换到何种字符集。默认为系统当前区域设置中所给定的字符集。
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fI文件名\fR
.RS 4
将所有信息输出至文件
\fI文件名\fR，而不是在命令行显示。尽管该操作可以用输出重定向轻松实现，但在特定情况下还是缺不得它：当终端写入文件之前重新解释（覆盖输出）时。
\fB\-\-output\-charset\fR
中所选定的字符集将被优先选用。
.RE
.PP
\fB\-\-ui\-language\fR \fI语言代码\fR
.RS 4
强制使用语言代码
\fI语言代码\fR
所对应的翻译（如 \*(Aqde_DE\*(Aq 对应德文翻译）。使用
\fILANG\fR、\fILC_MESSAGES\fR
及
\fILC_ALL\fR
这些环境变量更好。如果在
\fIcode\fR
处输入 \*(Aqlist\*(Aq，\fBmkvinfo\fR(1)
将输出可用翻译的列表。
.RE
.PP
\fB\-\-debug\fR \fI主题\fR
.RS 4
为特定功能开启调试。该选项仅对开发者有用。
.RE
.PP
\fB\-\-engage\fR \fI功能\fR
.RS 4
开启实验性功能。可用功能列表可通过
\fBmkvinfo \-\-engage list\fR
获取。通常情况下不应该使用这些功能。
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
使输出更详尽。请参阅关于
\(lq详细\(rq程度
的段落获取在哪些层级将输出哪些信息的描述。
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
显示用法信息并退出。
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
显示版本信息并退出。
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
联机下载 URL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]
以检查新版本。将以
键=值
的样式输出四行: 检索信息的 URL（键
version_check_url），当前运行的版本（键
running_version），最新版本号（键
available_version）及其下载 URL（键
download_url）。
.sp
若无更新版本可用，程序将以退出码 0 退出，若有更新版本可用，退出码为 1，若出现错误（如无法检索更新信息），退出码则为 2。
.sp
此选项仅当程序附带 libcurl 支持编译时可用。
.RE
.PP
\fB@\fR\fI选项文件\fR
.RS 4
从文件
\fI选项文件\fR
中读取额外的命令行参数。首个非空白字符为井号 (\*(Aq#\*(Aq) 的行将被当作注释对待，在处理过程中将被忽略。各行开头与结尾的空白将被除去。各行必须恰好仅含一个选项。
.sp
有些字符可以转义，如当您需要使用 \*(Aq#\*(Aq 作为一个不是评论的行的开头。规则在关于转义文本的段落有描述。
.sp
命令行 \*(Aq\fBmkvinfo \-v \-v 输入\&.mkv \-\-redirect\-output 信息\&.txt\fR\*(Aq 可以转换为下面所示的选项文件:
.sp
.if n \{\
.RS 4
.\}
.nf
# 更为详尽
\-v
\-v
# 解析 输入\&.mkv
输入\&.mkv
# 并将输出信息写入 信息\&.txt
\-\-redirect\-output
信息\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SH "\(lq详细\(rq程度"
.PP

\fB\-v\fR
选项可以使
\fBmkvinfo\fR(1)
增强其\(lq详细\(rq程度并输出关于当前文件的更多信息。
.PP
在 level 0
\fBmkvinfo\fR(1)
仅输出它发现的轨道头及其类型。头部解析完毕后（更专业地：遇到首个簇时），\fBmkvinfo\fR(1)
将退出执行。在此层级，定位头项与 cue 索引不会显示出来\(em\(em即使它们位于轨道信息之前。
.PP
在 level 1
\fBmkvinfo\fR(1)
同样将输出在整个文件中遇到的所有
Matroska(TM)
元素，此外还将输出定位头项与 cue 索引项。如果启用了简要模式，\fBmkvinfo\fR(1)
还将输出各帧位置。
.PP
在 level 2
\fBmkvinfo\fR(1)
同样将输出定位头项与 cue 索引项，以及文件中各
Matroska(TM)
元素被发现的位置。
.PP
在 level 3 及更高层级
\fBmkvinfo\fR(1)
将输出一些与
Matroska(TM)
元素不直接相连的信息。对于其他元素，将只输出发现的基本信息。Level 3 增加了元信息以便调试（换句话说：它是为开发人员设计的）。Level 3 输出的所有行都以方括号嵌套以便过滤。
.SH "退出代码"
.PP

\fBmkvinfo\fR(1)
退出时会返回以下三个退出代码中的一个：
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB0\fR
\-\- 此退出代码说明已成功完成运行。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB1\fR
\-\- 这种情况下
\fBmkvinfo\fR(1)
至少输出了一条警告信息，但运行并未因之中止。 警告信息以文字 \*(Aq警告:\*(Aq 为前缀。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB2\fR
\-\- 此退出代码用于错误发生之后。
\fBmkvinfo\fR(1)
在输出错误信息后即中断运行。错误信息可能是错误的命令行参数，也可能是损坏文件的读取/写入错误。
.RE
.SH "文本中特殊字符的转义"
.PP
有时文本中的特殊字符必须或应该转义。转义规则很简单: 用反斜杠后接一字符替换需要转义的各字符。
.PP
规则为: \*(Aq \*(Aq (空格) 变为 \*(Aq\es\*(Aq、\*(Aq"\*(Aq (双引号) 变为 \*(Aq\e2\*(Aq、\*(Aq:\*(Aq 变为 \*(Aq\ec\*(Aq、\*(Aq#\*(Aq 变为 \*(Aq\eh\*(Aq，而 \*(Aq\e\*(Aq (单个反斜杠) 自己则变为 \*(Aq\e\e\*(Aq。
.SH "环境变量"
.PP

\fBmkvinfo\fR(1)
会使用决定系统区域设置的默认变量 (如
\fILANG\fR
与
\fILC_*\fR
族)。其他变量包括:
.PP
\fIMKVTOOLNIX_DEBUG\fR 及其缩写形式 \fIMTX_DEBUG\fR
.RS 4
内容将被当作通过
\fB\-\-debug\fR
选项传递的参数对待。
.RE
.PP
\fIMKVTOOLNIX_ENGAGE\fR 及其缩写形式 \fIMTX_ENGAGE\fR
.RS 4
内容将被当作通过
\fB\-\-engage\fR
选项传递的参数对待。
.RE
.PP
\fIMKVTOOLNIX_OPTIONS\fR 及其缩写形式 \fIMTX_OPTIONS\fR
.RS 4
内容将在空白处切割。最终得到的字符串部分将按命令行选项的格式处理。如果您需要传递特殊字符 (如空白) 则需要转义 (参见关于转义文本中特殊字符的段落)。
.RE
.SH "参阅"
.PP

\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvpropedit\fR(1),
\fBmmg\fR(1)
.SH "网络"
.PP
最新版本总可以在
\m[blue]\fBMKVToolNix 主页\fR\m[]\&\s-2\u[1]\d\s+2
找到。
.SH "作者"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
开发者
.RE
.SH "备注"
.IP " 1." 4
MKVToolNix 主页
.RS 4
\%http://www.bunkus.org/videotools/mkvtoolnix/
.RE
