#!/bin/sh

if [ "$1" = "" ]; then
  echo 'Name?'
  exit 1
fi

N=`echo $1 | sed -e 's/\.rb//'`
cat > test-$N.rb <<EOF
#!/usr/bin/ruby -w

class T_${1} < Test
  def description
    return "INSERT DESCRIPTION"
  end

  def run
    # INSERT COMMANDS
    return nil
  end
end

EOF
