debian/tmp/bin/mkvmerge		/usr/bin
debian/tmp/bin/mkvinfo		/usr/bin
debian/tmp/bin/mkvextract	/usr/bin
debian/tmp/share/locale/de/LC_MESSAGES/mkvtoolnix.mo /usr/share/locale/de/LC_MESSAGES
debian/tmp/share/locale/ja/LC_MESSAGES/mkvtoolnix.mo /usr/share/locale/ja/LC_MESSAGES
debian/tmp/share/locale/zh_CN/LC_MESSAGES/mkvtoolnix.mo /usr/share/locale/zh_CN/LC_MESSAGES
debian/tmp/share/locale/zh_TW/LC_MESSAGES/mkvtoolnix.mo /usr/share/locale/zh_TW/LC_MESSAGES
