src/mmg/mmg-gui                              /usr/bin
src/mkvinfo-gui                              /usr/bin
share/desktop/*.desktop                      /usr/share/applications
share/mime/*.xml                             /usr/share/mime/packages
share/icons/16x16/*                          /usr/share/icons/hicolor/16x16/apps
share/icons/24x24/*                          /usr/share/icons/hicolor/24x24/apps
share/icons/32x32/*                          /usr/share/icons/hicolor/32x32/apps
share/icons/48x48/*                          /usr/share/icons/hicolor/48x48/apps
share/icons/64x64/*                          /usr/share/icons/hicolor/64x64/apps
share/icons/96x96/*                          /usr/share/icons/hicolor/96x96/apps
share/icons/128x128/*                        /usr/share/icons/hicolor/128x128/apps
share/icons/256x256/*                        /usr/share/icons/hicolor/256x256/apps
usr/share/doc/mkvtoolnix-gui/guide
