src/mmg/mmg-gui                              /usr/bin
src/mkvinfo-gui                              /usr/bin
share/desktop/*.desktop                      /usr/share/applications
share/mime/*.xml                             /usr/share/mime/packages
share/icons/32x32/*                          /usr/share/icons/hicolor/32x32/apps
share/icons/64x64/*                          /usr/share/icons/hicolor/64x64/apps
doc/guide/en/*.html doc/guide/en/*.hh?       /usr/share/doc/mkvtoolnix/guide/en
doc/guide/en/images/*                        /usr/share/doc/mkvtoolnix/guide/en/images
doc/guide/zh_CN/*.html doc/guide/zh_CN/*.hh? /usr/share/doc/mkvtoolnix/guide/zh_CN
doc/guide/zh_CN/images/*                     /usr/share/doc/mkvtoolnix/guide/zh_CN/images

