src/mmg/mmg-gui                              /usr/bin
src/mkvinfo-gui                              /usr/bin
share/desktop/*.desktop                      /usr/share/applications
share/mime/*.xml                             /usr/share/mime/packages
share/icons/32x32/*                          /usr/share/icons/hicolor/32x32/apps
share/icons/64x64/*                          /usr/share/icons/hicolor/64x64/apps
usr/share/doc/mkvtoolnix-gui/guide
