'\" t
.\"     Title: mkvinfo
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2013-09-16
.\"    Manual: Benutzerbefehle
.\"    Source: MKVToolNix 6.4.1
.\"  Language: German
.\"
.TH "MKVINFO" "1" "2013\-09\-16" "MKVToolNix 6\&.4\&.1" "Benutzerbefehle"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mkvinfo \- gibt Informationen \(:uber Elemente der Matroska(TM)\-Dateien aus\&.
.SH "\(:UBERSICHT"
.HP \w'\fBmkvinfo\fR\ 'u
\fBmkvinfo\fR [Optionen] {Quelldateiname}
.SH "BESCHREIBUNG"
.PP
Dieses Programm f\(:uhrt alle in
Matroska(TM)\-Dateien enthaltenen Elemente auf\&. Die Ausgabe kann kann auf eine Liste von Spuren in der Datei, einschlie\(sslich Informationen \(:uber die benutzten Codecs, begrenzt werden\&.
.PP
\fB\-g\fR, \fB\-\-gui\fR
.RS 4
startet das
GUI\&. Diese Option ist nur verf\(:ugbar, falls Mkvinfo mit
GUI\-Unterst\(:utzung kompiliert wurde\&.
.RE
.PP
\fB\-c\fR, \fB\-\-checksums\fR
.RS 4
berechnet f\(:ur jedes Bild die
\fBAdler32\fR\-Pr\(:ufsumme und zeigt sie an\&. Nur n\(:utzlich zur Fehlersuche\&.
.RE
.PP
\fB\-s\fR, \fB\-\-summary\fR
.RS 4
zeigt nur eine knappe Zusammenfassung, was
\fBmkvinfo\fR(1)
findet und nicht jedes Element\&.
.RE
.PP
\fB\-t\fR, \fB\-\-track\-info\fR
.RS 4
Zeigt detailliert Statistiken f\(:ur jede Spur an\&. Au\(sserdem wird die Detailstufe auf 1 gesetzt, falls sie vorher auf 0 war\&.
.RE
.PP
\fB\-x\fR, \fB\-\-hexdump\fR
.RS 4
zeigt die ersten 16 Byte jedes Bilds als hexadezimale Ausgabe an\&.
.RE
.PP
\fB\-X\fR, \fB\-\-full\-hexdump\fR
.RS 4
zeigt alle Byte von jedem Bild als hexadezimale Ausgabe an\&.
.RE
.PP
\fB\-z\fR, \fB\-\-size\fR
.RS 4
zeigt die Gr\(:o\(sse jedes Elements einschlie\(sslich seiner Kopfdaten an\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fIZeichensatz\fR
.RS 4
setzt den Zeichensatz, um auf der Befehlszeile angegebene Zeichenketten umzuwandeln\&. Voreinstellung ist der Zeichensatz der aktuellen Locale des Systems\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIZeichensatz\fR
.RS 4
setzt den Zeichensatz, in den Zeichenketten zur Ausgabe umgewandelt werden\&. Voreinstellung ist der Zeichensatz der aktuellen Locale des Systems\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fIDateiname\fR
.RS 4
schreibt alle Nachrichten in die Datei
\fIDateiname\fR
statt auf die Konsole\&. Obwohl dies einfach durch Ausgabeumleitung erledigt werden kann, gibt es F\(:alle, in denen diese Option ben\(:otigt wird: wenn das Terminal die Ausgabe vor dem Schreiben in eine Datei neu auswertet\&. Der mit
\fB\-\-output\-charset\fR
gesetzte Zeichensatz wird dabei ber\(:ucksichtigt\&.
.RE
.PP
\fB\-\-ui\-language\fR \fICode\fR
.RS 4
erzwingt, dass die \(:Ubersetzungen f\(:ur die Sprache
\fICode\fR
benutzt werden (z\&.B\&. \(Fcde_DE\(Fo f\(:ur die deutschen \(:Ubersetzungen)\&. Vorzugsweise sollten jedoch die Umgebungsvariablen
\fILANG\fR,
\fILC_MESSAGES\fR
und
\fILC_ALL\fR
benutzt werden\&. Die Eingabe von \(Fclist\(Fo als
\fICode\fR
wird
\fBmkvinfo\fR(1)
veranlassen, eine Liste der verf\(:ugbaren \(:Ubersetzungen auszugeben\&.
.RE
.PP
\fB\-\-debug\fR \fIThema\fR
.RS 4
schaltet die Fehlersuche f\(:ur eine bestimmte Funktionalit\(:at ein\&. Diese Option ist nur f\(:ur Entwicker n\(:utzlich\&.
.RE
.PP
\fB\-\-engage\fR \fIFunktionalit\(:at\fR
.RS 4
schaltet experimentelle Funktionalit\(:aten ein\&. Eine Liste verf\(:ugbarer Funktionalit\(:aten kann mit
\fBmkvinfo \-\-engage list\fR
abgefragt werden\&. Diese Funktionalit\(:aten sind nicht f\(:ur die Verwendung in Alltagssituationen gedacht\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
erh\(:oht die Dateilstufe\&. Welche Beschreibung auf welcher Stufe ausgegeben wird, finden Sie im Abschnitt
Detailstufen\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
zeigt Benutzungsinformationen und beendet sich\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
zeigt Versionsinformationen und beendet sich\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
pr\(:uft online durch Herunterladen der URL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[], ob es neue Ver\(:offentlichungen gibt\&. Vier Zeilen werden im Stil
Schl\(:ussel=Wert
ausgegeben: die URL, von der die Informationen bezogen wurden (Schl\(:ussel
version_check_url), die aktuell laufende Version (Schl\(:ussel
running_version), die Version der neusten Ver\(:offentlichung (Schl\(:ussel
available_version) und die Download\-URL (Schl\(:ussel
download_url)\&.
.sp
Anschlie\(ssend beendet sich das Programm mit einem R\(:uckgabewert von 0, falls keine neuere Ver\(:offentlichung verf\(:ugbar ist, mit 1, wenn eine neuere Ver\(:offentlichung verf\(:ugbar ist und mit 2, falls ein Fehler auftritt (z\&.B\&., wenn die Aktualisierungsinformationen nicht abgefragt werden konnten)\&.
.sp
Diese Option ist nur verf\(:ugbar, falls das Programm mit Unterst\(:utzung f\(:ur Libcurl gebaut wurde\&.
.RE
.PP
\fB@\fR\fIOptionsdatei\fR
.RS 4
liest zus\(:atzliche Befehlszeilenargumente aus der Datei
\fIOptionsdatei\fR\&. Zeilen, deren erstes Nichtleerraumzeichen ein Rautenzeichen (\(Fc#\(Fo) ist, werden als Kommentare betrachtet und ignoriert\&. Leerr\(:aume am Anfang und Ende einer Zeile werden abgeschnitten\&. Jede Zeile darf genau eine Option enthalten\&.
.sp
Verschiedene Zeichen k\(:onnen maskiert werden, z\&.B\&. falls Sie m\(:ochten, dass eine Nichtkommentarzeile mit einem \(Fc#\(Fo beginnt\&. Die Regeln werden im
Abschnitt \(:uber Maskieren von Text
beschrieben\&.
.sp
Die Befehlszeile \(Fc\fBmkvinfo \-v \-v Eingabe\&.mkv \-\-redirect\-output Info\&.txt\fR
kann in die folgende Optionsdatei umgewandelt werden:
.sp
.if n \{\
.RS 4
.\}
.nf
# Detailstufe erh\(:ohen
\-v
\-v
# Eingabe\&.mkv auswerten
Eingabe\&.mkv
# und die Ausgabe in Info\&.txt schreiben
\-\-redirect\-output
Info\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SH "DETAILSTUFEN"
.PP
Die Option
\fB\-v\fR
kann benutzt werden, um die Detailstufe von
\fBmkvinfo\fR(1)
zu erh\(:ohen und weitere Informationen \(:uber die aktuelle Datei auszugeben\&.
.PP
Auf Stufe 0 wird
\fBmkvinfo\fR(1)
nur die Spurkopfdaten, die es findet und deren Typen, ausgeben\&. Sobald die Kopfdaten vollst\(:andig ausgewertet sind, wird sich
\fBmkvinfo\fR(1)
beenden (technischer ausgedr\(:uckt: sobald der erste Cluster gefunden wird)\&. Auf dieser Stufe werden die Suchkopfeintr\(:age und Indizes nicht angezeigt \(en selbst wenn sie vor den Spurinformationen liegen\&.
.PP
Auf Stufe 1 wird
\fBmkvinfo\fR(1)
ebenfalls alle f\(:ur die vollst\(:andige Datei gefundenen
Matroska(TM)\-Elemente au\(sser den Suchkopf\- und Indexeintr\(:agen ausgeben\&. Falls der Zusammenfassungsmodus aktiviert ist, wird
\fBmkvinfo\fR(1)
obendrein die Bildposition ausgeben\&.
.PP
Auf Stufe 2 wird
\fBmkvinfo\fR(1)
auch die Suchkopfeintr\(:age, die Indexeintr\(:age und die Dateiposition ausgeben, an der jedes
Matroska(TM)\-Element gefunden werden kann\&.
.PP
Auf Stufe 3 und dar\(:uber wird
\fBmkvinfo\fR(1)
einige Informationen ausgeben, die nicht direkt mit einem
Matroska(TM)\-Element verbunden sind\&. Alle anderen Elemente geben nur Zeug \(:uber Elemente aus, die soeben gefunden wurden\&. Stufe 3 f\(:ugt Metainformationen zur Erleichterung der Fehlersuche hinzu (sprich: Sie ist nur f\(:ur Entwickler gedacht)\&. Alle Zeilen, die durch Stufe 3 geschrieben werden, sind in eckige Klammern eingeschlossen, um ihre Filterung zu erleichtern\&.
.SH "R\(:UCKGABEWERTE"
.PP
\fBmkvinfo\fR(1)
beendet sich mit einem von drei R\(:uckgabewerten:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\(en dieser R\(:uckgabewert bedeutet, dass der Durchlauf erfolgreich abgeschlossen wurde\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\(en in diesem Fall hat
\fBmkvinfo\fR(1)
mindestens eine Warnung ausgegeben, die Ausf\(:uhrung wurde aber fortgesetzt\&. Einer Warnung wird der Text \(FcWarning:\(Fo vorangestellt\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\(en dieser R\(:uckgabewert wird benutzt, nachdem ein Fehler aufgetreten ist\&.
\fBmkvinfo\fR(1)
wird gleich nach der Ausgabe der Fehlermeldung abgebrochen\&. Fehlermeldungen reichen von falschen Befehlszeilenargumenten \(:uber Lese\-/Schreibfehler bis hin zu besch\(:adigten Dateien\&.
.RE
.SH "SONDERZEICHEN IN TEXT MASKIEREN"
.PP
Es gibt ein paar Stellen, an denen Sonderzeichen in Text maskiert werden m\(:ussen oder sollen\&. Die Regeln zum Maskieren sind einfach: Jedes Zeichen, das maskiert werden soll, wird durch einen R\(:uckw\(:artsschr\(:agstrich gefolgt von einem weiteren Zeichen ersetzt\&.
.PP
Die Regeln lauten: \(Fc \(Fo (ein Leerzeichen) wird \(Fc\es\(Fo, \(Fc"\(Fo (doppeltes Anf\(:uhrungszeichen) wird \(Fc\e2\(Fo, \(Fc:\(Fo wird \(Fc\ec\(Fo, \(Fc#\(Fo wird \(Fc\eh\(Fo und \(Fc\e\(Fo (ein einfacher R\(:uckw\(:artsschr\(:agstrich selbst) wird \(Fc\e\e\(Fo\&.
.SH "UMGEBUNGSVARIABLEN"
.PP
\fBmkvinfo\fR(1)
verwendet die Standardvariablen, um die Locale des Systems zu bestimmen (z\&.B\&.
\fILANG\fR
und die
\fILC_*\fR\-Familie)\&. Zus\(:atzliche Variablen:
.PP
\fIMKVTOOLNIX_DEBUG\fR und ihre Kurzform \fIMTX_DEBUG\fR
.RS 4
Der Inhalt wird behandelt, als ob er mit der Option
\fB\-\-debug\fR
\(:ubergeben worden w\(:are\&.
.RE
.PP
\fIMKVTOOLNIX_ENGAGE\fR und ihre Kurzform \fIMTX_ENGAGE\fR
.RS 4
Der Inhalt wird behandelt, als ob er mit der Option
\fB\-\-engage\fR
\(:ubergeben worden w\(:are\&.
.RE
.PP
\fIMKVTOOLNIX_OPTIONS\fR und ihre Kurzform \fIMTX_OPTIONS\fR
.RS 4
Der Inhalt wird bei Leerr\(:aumen aufgeteilt\&. Die resultierenden Teilzeichenketten werden behandelt, als ob sie als Befehlszeilenoptionen \(:ubergeben worden w\(:aren\&. Falls Sie Sonderzeichen \(:ubergeben m\(:ochten (z\&.B\&. Leerzeichen), m\(:ussen Sie sie maskieren (siehe
den Abschnitt \(:uber Maskieren von Sonderzeichen in Text)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvpropedit\fR(1),
\fBmmg\fR(1)
.SH "WWW"
.PP
Die neuste Version kann immer auf
\m[blue]\fBder MKVToolNix\-Homepage\fR\m[]\&\s-2\u[1]\d\s+2
gefunden werden\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Entwickler
.RE
.SH "FU\(ssNOTEN"
.IP " 1." 4
der MKVToolNix-Homepage
.RS 4
\%http://www.bunkus.org/videotools/mkvtoolnix/
.RE
