'\" t
.\"     Title: mkvmerge
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.78.0 <http://docbook.sf.net/>
.\"      Date: 2013-02-26
.\"    Manual: Gebruiker commando\*(Aqs
.\"    Source: MKVToolNix 6.1.0
.\"  Language: Dutch
.\"
.TH "MKVMERGE" "1" "2013\-02\-26" "MKVToolNix 6\&.1\&.0" "Gebruiker commando\*(Aqs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mkvmerge \- Voegt multimedia stromen in een Matroska(TM) bestand in\&.
.SH "BEKNOPTE INHOUDSBESCHRIJVING"
.HP \w'\fBmkvmerge\fR\ 'u
\fBmkvmerge\fR [global\ options] {\-o\ out} [options1] {file1} [[options2]\ {file2}] [@optionsfile]
.SH "BESCHRIJVING"
.PP
Dit programma neemt de invoer van verschillende media bestanden en voegt die stromen samen (allemaal of slechts een stukje) naar een
Matroska(TM)
bestand; zie de
\m[blue]\fBMatroska(TM)\fR\m[]\&\s-2\u[1]\d\s+2
website\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBBelangrijk\fR
.ps -1
.br
.PP
De volgorde van het commando regel opties zijn belangrijk\&. Lees a\&.u\&.b\&. de sectie over:
"Optie volgorde"
als je nog onbekend bent met het programma\&.
.sp .5v
.RE
.SS "Globale opties"
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Verhoog \*(Aquitgebreidheid\*(Aq\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Onderdruk status uitvoer\&.
.RE
.PP
\fB\-o\fR, \fB\-\-output\fR \fIfile\-name\fR
.RS 4
Schrijf naar het bestand
\fIfile\-name\fR\&. Indien splitsen aan staat, dan wordt dat iets anders verwerkt\&. Zie uitleg voor de
\fB\-\-split\fR
optie voor details\&.
.RE
.PP
\fB\-w\fR, \fB\-\-webm\fR
.RS 4
Cre\(:eer een WebM herkenbaar bestand\&. mkvmerge zet dit tevens aan wanneer het uitvoerbestandsnaam de extensie "webm" heeft\&. Deze modus dwingt diverse beperkingen af\&. De enig toegestane codecs zijn VP8 video en Vorbis audio sporen\&. G\('e\('en van het volgende hoofdstuk markeringen zijn toegestaan\&. Het DocType kop item is veranderd naar "webm"\&.
.RE
.PP
\fB\-\-title\fR \fItitle\fR
.RS 4
Stelt de algemene naam in voor de uitvoer bestand, b\&.v\&. de film naam\&.
.RE
.PP
\fB\-\-default\-language\fR \fIlanguage\-code\fR
.RS 4
Stelt de standaard land code in voor alle sporen tenzij die wordt overschreven met
\fB\-\-language\fR
optie\&. De standaard code is \*(Aqonb\*(Aq voor \*(Aqonbekend\*(Aq\&.
.RE
.SS "Hanteren van segment informatie (globale opties)"
.PP
\fB\-\-segmentinfo\fR \fIfilename\&.xml\fR
.RS 4
Leest segment informatie in van een
XML
bestand\&. Dit bestand kan de segment familie bevatten
UID, segment
UID, vorige en volgend segment
UID
elementen\&. een voorbeeld bestand en een
DTD
zijn ingesloten in de MKVToolNix distributie\&.
.sp
Zie de sectie over:
Het segment informatie XML bestanden
zie hieronder voor details\&.
.RE
.PP
\fB\-\-segment\-uid\fR \fISID1,SID2,\&.\&.\&.\fR
.RS 4
Stelt het te gebruiken segment UID\*(Aqs in\&. Dit is een komma gesepareerde lijst van 128bit segment UID\*(Aqs in het gebruikelijke UID formaat: hex nummers met of zonder de "0x" voorzetsel, met of zonder spaties, exact 32 cijfers\&.
.sp
Elk gecre\(:eerd bestand bevat \('e\('en segment, en elk segment heeft \('e\('en UID\&. Als er meer segment UID\*(Aqs zijn opgegeven dan er zijn gecre\(:eerd, dan zullen de extra UID\*(Aqs worden genegeerd\&. Zijn er minder UID\*(Aqs opgegeven dan er segmenten zijn gecre\(:eerd, dan worden er willekeurig UID\*(Aqs voor hen aangemaakt\&.
.RE
.SS "Hanteren hoofdstuk en markeringen (globale opties)"
.PP
\fB\-\-chapter\-language\fR \fIlanguage\-code\fR
.RS 4
Stelt de ISO639\-2 land code waarde in welke geschreven wordt voor elk hoofdstuk ingang\&. Standaard naar \*(Aqeng\*(Aq\&. Zie de sectie over:
Hoofdstukken
hieronder voor details\&.
.sp
Deze optie kan gebruikt worden, voor simpele hoofdstukken en voor bronbestanden welke hoofdstukken bevatten maar geen informatie over hoofdstuk talen, b\&.v\&. MP4 en OGM bestanden\&.
.RE
.PP
\fB\-\-chapter\-charset\fR \fIcharacter\-set\fR
.RS 4
Stelt het karakter set in, die gebruikt wordt voor de UTF\-8 conversie voor simpele hoofdstuk bestanden\&. Zie de sectie over:
Tekst bestanden en karakter set conversies
voor een uitleg hoe
\fBmkvmerge\fR(1)
converteert tussen het \*(Aqverschillende\*(Aq karakter sets\&.
.sp
Deze schakelaar is ook van toepassing op hoofdstukken die zijn gekopieerd van enkele bepaalde inhoudstypen, b\&.v\&. Ogg/OGM en MP4 bestanden\&. Zie de sectie over hoofdstukken hieronder voor details\&.
.RE
.PP
\fB\-\-cue\-chapter\-name\-format\fR \fIformat\fR
.RS 4

\fBmkvmerge\fR(1)
ondersteund lezen van
CUE
volg document(en) (cue) voor audio bestanden als invoer voor hoofdstukken\&.
CUE
volg document(en) (cue) bevatten gewoonlijk informatie over de
\fIARTIEST\fR
en
\fITITEL\fR
voor elke index ingang\&.
\fBmkvmerge\fR(1)
gebruikt deze twee reeksen om het hoofdstuknaam te construeren\&. Met deze optie kan het formaat dat voor deze naam wordt gebruikt worden geplaatst\&.
.sp
Is deze optie niet opgegeven, dan zal
\fBmkvmerge\fR(1)
het standaard format gebruiken \*(Aq%p \- %t\*(Aq (de artiest (performer), gevolgd door een spatie, een streep, wederom een spatie en de titel)\&.
.sp
Is de format opgegeven dan zal alles behalve de volgende meta karakters gekopieerd worden zoals ze zijn, en de meta karakters worden vervangen zoals dit:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI%p\fR
is vervangen door de huidige ingangen
\fIPERFORMER\fR
(artiest) reeks,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI%t\fR
is vervangen door de huidige ingangen
\fITITLE\fR
(titel) reeks,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI%n\fR
wordt vervangen op huidig spoor nummer en
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI%N\fR
wordt vervangen op huidig spoor nummer en op/aangevuld met een beginnend/leidende nul als het is < 10 (kleiner dan)\&.
.RE
.RE
.PP
\fB\-\-chapters\fR \fIfile\-name\fR
.RS 4
Leest hoofdstuk informatie in van een bestand
\fIfile\-name\fR\&. Zie sectie over:
Hoofdstukken
kijk hieronder voor details\&.
.RE
.PP
\fB\-\-global\-tags\fR \fIfile\-name\fR
.RS 4
Leest hoofdstuk informatie in van een bestand
\fIfile\-name\fR\&. Zie sectie over:
Hoofdstukken
kijk hieronder voor details\&.
.RE
.SS "Algemene uitvoer controle (geavanceerde globale opties)"
.PP
\fB\-\-track\-order\fR \fIFID1:TID1,FID2:TID2,\&.\&.\&.\fR
.RS 4
Deze optie verandert de volgorde waarin de sporen voor een invoer bestand worden gecre\(:eerd\&. Het argument is een komma gescheiden lijst van gepaarde ID\*(Aqs\&. Elk paar bevat eerst het bestand ID (\fIFID1\fR) wat simpelweg een nummer van het bestand is op de commandoregel beginnend bij 0\&. Het tweede is een spoor ID (\fITID1\fR) van dat bestand\&. Als sommige spoor id\*(Aqs worden weggelaten, dan zullen die sporen worden gecre\(:eerd na diegene die met deze optie zijn gecre\(:eerd\&.
.RE
.PP
\fB\-\-cluster\-length\fR \fIspec\fR
.RS 4
Limiteert het aantal data blokken of de duur van de data in elke cluster\&. De
\fIspec\fR
parameter kan \('e\('en van beide zijn een nummer
\fIn\fR
zonder een eenheid of een nummer
\fId\fR
vastgezet met \*(Aqms\*(Aq (milliseconden)\&.
.sp
Als er geen eenheid is gebruikt dan zal
\fBmkvmerge\fR(1)
hoogstens zetten
\fIn\fR
data blokken in elke cluster\&. Het maximum aantal blokken is 65535\&.
.sp
Als het nummer
\fId\fR
is vastgezet met \*(Aqms\*(Aq dan zal
\fBmkvmerge\fR(1)
hoogstens zetten
\fId\fR
milliseconden aan data in elke cluster\&. Het minimum voor
\fId\fR
is \*(Aq100ms\*(Aq, en het maximum is \*(Aq32000ms\*(Aq\&.
.sp

\fBmkvmerge\fR(1)
plaatst standaard op zijn hoogst 65535 data blokken en 5000ms aan data in een cluster\&.
.sp
Programma\*(Aqs die een bepaald beeld proberen te zoeken, kunnen alleen direct naar een cluster zoeken en moeten daarna de gehele cluster lezen\&. Daarom kan het de oorzaak zijn, dat het maken van grote clusters kan leiden tot onnauwkeurigheid of traag zoeken\&.
.RE
.PP
\fB\-\-no\-cues\fR
.RS 4
Vertelt
\fBmkvmerge\fR(1)
geen volg document(en) (cue) te cre\(:eren en te schrijven wat vergelijkbaar is met een index in een AVI\&.
Matroska(TM)
bestanden kunnen worden afgespeeld zonder volg document(en) (cue), maar dat kan leiden tot onnauwkeurigheid of traag zoeken\&. Gebruik dit alleen als je echt wanhopig bent qua ruimte of voor test doeleinden\&. Zie ook de optie
\fBvolg document(en) (cue)\fR
welke opgegeven kan worden voor elk invoer bestand\&.
.RE
.PP
\fB\-\-clusters\-in\-meta\-seek\fR
.RS 4
Vertelt
\fBmkvmerge\fR(1)
een meta element te cre\(:eren aan het eind van het bestand dat alle clusters bevat\&. Zie ook de sectie over:
Matroska(TM) bestand layout\&.
.RE
.PP
\fB\-\-disable\-lacing\fR
.RS 4
Zet het aaneenkoppelen uit voor alle sporen\&. Dit zal de bestandsgrootte verhogen, speciaal wanneer er veel audio sporen zijn\&. Deze optie is niet bedoeld voor dagelijks gebruik\&.
.RE
.PP
\fB\-\-enable\-durations\fR
.RS 4
Duur schrijven voor alle blokken\&. Dit zal de bestandsgrootte verhogen en geeft geen extra waarde aan af spelers van dit moment\&.
.RE
.PP
\fB\-\-timecode\-scale\fR \fIfactor\fR
.RS 4
Forceert de tijd code schaal factor naar
\fIfactor\fR\&. Geldige bereik waardes zijn
\fB1000\fR\&.\&.\fB10000000\fR
of de speciale waarde
\fB\-1\fR\&.
.sp
Normaal zal
\fBmkvmerge\fR(1)
een waarde gebruiken van
\fB1000000\fR
wat inhoudt, dat de tijd codes en duren een precisie hebben van 1ms\&. Voor bestanden die geen video maar minstends \('e\('en audio spoor bevatten, zal
\fBmkvmerge\fR(1)
automatisch de tijd code schaal factor kiezen, zodat alle tijd codes en duren een precisie hebben van \('e\('en audio voorbeeld\&. Dit veroorzaakt een grotere overhead maar staat een betere zoek en extractie precisie toe\&.
.sp
Als de speciale waarde
\fB\-1\fR
is gebruikt, dan zal
\fBmkvmerge\fR(1)
een voorbeeld precisie gebruiken zelfs als er een video spoor aanwezig is\&.
.RE
.SS "Bestand splitsen, linken en toevoegen (meer globale opties)"
.PP
\fB\-\-split\fR \fIspecification\fR
.RS 4
Splits de uitvoer bestand na een opgegeven grootte of tijd\&. Opmerking, sporen kunnen all\('e\('en direct voor een sleutel beeld gesplitst worden\&. Vanwege het bufferen zal
\fBmkvmerge\fR(1)
als een splitspunt wordt bereikt, direct voor het volgende sleutel beeld gaan splitsen\&. Daarom kunnen de splitspunten enigszins afwijken van wat de gebruiker op gaf\&.
.sp
Op het moment ondersteunt
\fBmkvmerge\fR(1)
vier verschillende modes\&.
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Splitsen op grootte\&.
.sp
Ingaven:
\fB\-\-split\fR
[size:]\fId\fR[k|m|g]
.sp
Voorbeelden:
\-\-split size:700m
of
\-\-split 150000000
.sp
De parameter
\fId\fR
mag eindigen met \*(Aqk\*(Aq, \*(Aqm\*(Aq of \*(Aqg\*(Aq ter indicatie dat de grootte respectievelijk wordt aangegeven in KB, MB of GB\&. Anders wordt een grootte in Bytes verondersteld\&. Nadat een uitvoer bestand zijn limiet heeft bereikt wordt er een andere aangemaakt\&.
.sp
De \*(Aqsize:\*(Aq mag vanwege de verenigbaarheid (compatibiliteit) weggelaten worden\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Splitsen na een duur van\&.
.sp
Ingaven:
\fB\-\-split\fR
[duur:]\fIHH:MM:SS\&.nnnnnnnnn\fR|\fId\fRs
.sp
Voorbeeld:
\-\-split duration:00:60:00\&.000
of
\-\-split 3600s
.sp
De parameter moet \('e\('en van beiden de vormen hebben
\fIHH:MM:SS\&.nnnnnnnnn\fR
voor het specificeren van de duur tot in de precisie van een nanoseconde of een nummer
\fId\fR
gevolgd door een letter \*(Aqs\*(Aq voor de duur in seconden\&.
\fIHH\fR
is het aantal uren,
\fIMM\fR
het aantal minuten,
\fISS\fR
het aantal seconden en
\fInnnnnnnnn\fR
het aantal nanoseconden\&. Zowel de uren evenals de nanoseconden mogen weggelaten worden\&. Er mogen tot aan negen nummers opgegeven worden na de decimale punt\&. Nadat de duur van de huidige inhoud deze limiet bereikt heeft, wordt er een nieuw uitvoer bestand gestart\&.
.sp
De \*(Aqduration:\*(Aq mag vanwege de verenigbaarheid (compatibiliteit) weggelaten worden\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Splitsen na een specifieke tijd code\&.
.sp
Ingaven:
\fB\-\-split\fR
timecodes:\fIA\fR[,\fIB\fR[,\fIC\fR\&.\&.\&.]]
.sp
Voorbeeld:
\-\-split timecodes:00:45:00\&.000,01:20:00\&.250,6300s
.sp
De parameters
\fIA\fR,
\fIB\fR,
\fIC\fR
etc\&. moeten allen dezelfde indeling hebben als de duur (zie hierboven)\&. De lijst van tijd codes is komma gescheiden\&. Nadat de uitvoer stroom zijn huidige splits tijd code limiet heeft bereikt wordt er een nieuw bestand gecre\(:eerd\&. Daarna wordt het volgende splits punt gebruikt van de gebruikte lijst\&.
.sp
Het \*(Aqtimecodes:\*(Aq voorvoegsel mag niet wegelaten worden\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Houden van specifieke delen door het specificeren van tijd code bereiken, terwijl het van anderen ontdaan wordt\&.
.sp
Ingaven:
\fB\-\-split\fR
parts:\fIstart1\fR\-\fIend1\fR[,[+]\fIstart2\fR\-\fIend2\fR[,[+]\fIstart3\fR\-\fIend3\fR\&.\&.\&.]]
.sp
Voorbeeld:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
\-\-split parts:00:01:20\-00:02:45,00:05:50\-00:10:30
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
\-\-split parts:00:01:20\-00:02:45,+00:05:50\-00:10:30
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
\-\-split parts:\-00:02:45,00:05:50\-
.RE
.sp
De
parts
mode vertelt
\fBmkvmerge\fR(1)
bepaalde tijd code bereiken te behouden en anderen over te slaan\&. De te behouden bereiken worden uit gelijst na de
parts:
sleutelwoord en gescheiden door een komma\&. Het bereik zelf bestaat uit een start en een eindtijd code in hetzelfde format als de overige variaties van
\fI\-\-split\fR
accept (b\&.v\&. beide
00:01:20
en
80s
verwijzen naar dezelfde tijd code)\&.
.sp
Als een start tijd code is weggelaten wordt het standaard gezet naar het vorige bereik eindtijd code\&. Als er geen vorig bereik, dan is standaard het begin van het bestand (zie voorbeeld 3)\&.
.sp
Als een eind tijd code is weggelaten, dan is standaard het einde van de bronbestanden die in feite
\fBmkvmerge\fR(1)
vertelt om de rest te houden (zie voorbeeld 3)
.sp
Normaal gesproken wordt elk bereik weggeschreven naar een nieuw bestand\&. Dit kan worden veranderd, zodat opeenvolgende reeksen worden geschreven in hetzelfde bestand\&. Daarvoor moet de gebruiker de start tijd code voorzetten met een
+\&. Dit vertelt
\fBmkvmerge\fR(1)
om niet een nieuw bestand aan te maken en in plaats daarvan het bereik toe te voegen aan hetzelfde bestand die in de vorige reeks is geschreven\&. Tijdcodes zullen worden aangepast, zodat er g\('e\('en gat ontstaat in het uitvoerbestand, zelfs als er een gat in de twee bereiken in het invoerbestand waren\&.
.sp
In voorbeeld 1 zal
\fBmkvmerge\fR(1)
twee bestanden aanmaken\&. De eerste bevat de inhoud startend vanaf
00:01:20
tot
00:02:45\&. De tweede zal de inhoud bevatten vanaf
00:05:50
tot
00:10:30\&.
.sp
In voorbeeld 2 zal
\fBmkvmerge\fR(1)
slechts \('e\('en bestand aanmaken\&. Dit bestand zal beide inhoud bevatten startend van
00:01:20
tot
00:02:45
en de inhoud startend van
00:05:50
tot
00:10:30\&.
.sp
In voorbeeld 3 zal
\fBmkvmerge\fR(1)
twee bestanden aanmaken\&. De eerste bevat de inhoud vanaf het beging van het bron bestanden tot
00:02:45\&. Het tweede bevat de inhoud startend vanaf
00:05:50
tot het eind van het bron bestanden\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOpmerking\fR
.ps -1
.br
Opmerking, dat
\fBmkvmerge\fR(1)
alleen beslissingen neemt over het splitsen op sleutel beeld posities\&. Dit geldt voor zowel voor het begin en het einde van elk bereik\&. Dus zelfs als een eind tijdcode tussen twee sleutel beelden ligt, blijft
\fBmkvmerge\fR(1)
beelden uitvoeren tot aan, maar exclusief de volgende sleutel beeld\&.
.sp .5v
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Houden van specifieke delen door het specificeren van beeld/veld nummer bereiken, terwijl het van anderen ontdaan wordt\&.
.sp
Ingaven:
\fB\-\-split\fR
parts\-frames:\fIstart1\fR\-\fIend1\fR[,[+]\fIstart2\fR\-\fIend2\fR[,[+]\fIstart3\fR\-\fIend3\fR\&.\&.\&.]]
.sp
Voorbeeld:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
\-\-split parts\-frames:137\-258,548\-1211
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
\-\-split parts\-frames:733\-912,+1592\-2730
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
\-\-split parts\-frames:\-430,2512\-
.RE
.sp
De
parts\-frames
mode vertelt
\fBmkvmerge\fR(1)
bepaalde bereiken van beeld/veld nummers te behouden en anderen over te slaan\&. De te behouden bereiken moeten uit gelijst worden na de
parts\-frames:
sleutelwoord en gescheiden door een komma\&. Het bereik zelf bestaat uit een start en een eind beeld/veld nummer\&. Nummering start op 1\&.
.sp
Als een start nummer is weggelaten wordt het standaard gezet naar het vorige bereik eind nummer\&. Als er geen vorig bereik is, dan is standaard het begin van het bestand (zie voorbeeld 3)\&.
.sp
Als een eind nummer is weggelaten, dan is standaard het einde van de bronbestanden die in feite
\fBmkvmerge\fR(1)
vertelt om de rest te behouden (zie voorbeeld 3)
.sp
Normaal gesproken, wordt elk bereik weggeschreven naar een nieuw bestand\&. Dit kan worden veranderd, zodat opeenvolgende reeksen worden geschreven in hetzelfde bestand\&. Daarvoor, moet de gebruiker het start nummer voorzetten met een
+\&. Dit vertelt
\fBmkvmerge\fR(1)
om niet een nieuw bestand aan te maken en in plaats daarvan, het bereik toe te voegen aan hetzelfde bestand die in de vorige reeks werd geschreven\&. Tijdcodes zullen worden aangepast, zodat er g\('e\('en gat ontstaat in het uitvoerbestand, zelfs als er een gat in de twee bereiken in het invoerbestand waren\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOpmerking\fR
.ps -1
.br
Opmerking, dat
\fBmkvmerge\fR(1)
alleen beslissingen neemt over het splitsen op sleutel beeld posities\&. Dit geldt voor zowel voor het begin en het einde van elk bereik\&. Dus zelfs als een eind beeld/veld nummer tussen twee sleutel beelden ligt, blijft
\fBmkvmerge\fR(1)
beelden uitvoeren tot aan, maar exclusief de volgende sleutel beeld\&.
.sp .5v
.RE
In voorbeeld 1 zal
\fBmkvmerge\fR(1)
twee bestanden aanmaken\&. De eerste bevat de inhoud startend op of na het eerste sleutel beeld
137
maar exclusief het eerste sleutel beeld op of na
258\&. Het tweede bestand, zal de inhoud bevatten startend vanaf
548
tot
1211\&.
.sp
In voorbeeld 2 zal
\fBmkvmerge\fR(1)
slechts \('e\('en bestand aanmaken\&. Dit bestand zal beide inhoud bevatten startend van
733
tot
912
en de inhoud startend vanaf
1592
tot
2730\&.
.sp
In voorbeeld 3 zal
\fBmkvmerge\fR(1)
twee bestanden aanmaken\&. De eerste bevat de inhoud vanaf het begin van het bron bestanden tot
430\&. Het tweede bevat de inhoud startend vanaf
2512
tot het eind van het bron bestanden\&.
.sp
Deze modus houdt alleen rekening met de eerste video spoor dat wordt uitgevoerd\&. Als er geen video spoor is uitgevoerd dan zal splitsen niet plaatsvinden\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOpmerking\fR
.ps -1
.br
De getallen met dit argument worden ge\(:interpreteerd op basis van het aantal
Matroska(TM)
blokken die worden uitgevoerd\&. Een enkele
Matroska(TM)
blok bevat ofwel een volledig beeld (voor progressieve inhoud) of een enkel veld (voor interlaced inhoud)\&. mkvmerge maakt geen onderscheid tussen die twee en telt eenvoudig telt aantal blokken\&. Als voorbeeld: Als men wilt verdelen na het 25ste volledige beeld met interlaced inhoud zou men
50
moeten gebruiken (twee velden per volledig beeld) als splits moment\&.
.sp .5v
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
Splitsen na specifieke beelden/velden codes\&.
.sp
Ingaven:
\fB\-\-split\fR
frames:\fIA\fR[,\fIB\fR[,\fIC\fR\&.\&.\&.]]
.sp
Voorbeeld:
\-\-split frames:120,237,891
.sp
De parameters
\fIA\fR,
\fIB\fR,
\fIC\fR
etc\&. moeten allen positieve cijfers bevatten\&. Nummering start vanaf 1\&. De lijst van beeld/veld codes is komma gescheiden\&. Nadat de uitvoer stroom zijn huidige splits tijd code limiet heeft bereikt wordt er een nieuw bestand gecre\(:eerd\&. Daarna wordt het volgende splits punt gebruikt van de gebruikte lijst\&.
.sp
Het \*(Aqframes:\*(Aq voorvoegsel mag niet wegelaten worden\&.
.sp
Deze modus houdt alleen rekening met de eerste video spoor dat wordt uitgevoerd\&. Als er geen video spoor is uitgevoerd dan zal splitsen niet plaatsvinden\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOpmerking\fR
.ps -1
.br
De getallen met dit argument worden ge\(:interpreteerd op basis van het aantal
Matroska(TM)
blokken die worden uitgevoerd\&. Een enkele
Matroska(TM)
blok bevat ofwel een volledig beeld (voor progressieve inhoud) of een enkel veld (voor interlaced inhoud)\&. mkvmerge maakt geen onderscheid tussen die twee en telt eenvoudig telt aantal blokken\&. Als voorbeeld: Als men wilt verdelen na het 25ste volledige beeld met interlaced inhoud zou men
50
moeten gebruiken (twee velden per volledig beeld) als splits moment\&.
.sp .5v
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 7.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  7." 4.2
.\}
Splitsen na een specifieke hoofstukken\&.
.sp
Syntax:
\fB\-\-split\fR
chapters:all
or
\fB\-\-split\fR
chapters:\fIA\fR[,\fIB\fR[,\fIC\fR\&.\&.\&.]]
.sp
Voorbeeld:
\-\-split chapters:5,8
.sp
De parameters
\fIA\fR,
\fIB\fR,
\fIC\fR
etc\&. moeten allen positief zijn\&. Nummering start vanaf 1\&. De lijst van hoofstukken is komma gescheiden\&. Splitsing zal plaatsvinden vlak voor het eerste toets sleutelbeeld waarvan de tijd code gelijk is aan of groter is dan de start tijd code voor de hoofdstukken waarvan de nummers zijn opgenomen\&. Een hoofdstuk vanaf 0s wordt nooit beschouwd voor het splitsen en wordt geruisloos weggegooid\&.
.sp
Het sleutelwoord
all
kan worden gebruikt i\&.p\&.v\&. alle hoofdstuknummers handmatig uit te lijsten\&.
.sp
Het
chapters:\*(Aq voorvoegsel mag niet wegelaten worden\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOpmerking\fR
.ps -1
.br
Het
Matroska(TM)
bestandsformaat ondersteunt willekeurige diep geneste hoofdstuk structuren, genoemd \*(Aqeditie ingaven\*(Aq en \*(Aqhoofdstuk delen\*(Aq\&. Echter, deze modus beperkt zich alleen tot het hoogste niveau van de hoofdstukken door alle editie ingaven\&.
.sp .5v
.RE
.RE
.sp
Voor deze splits mode wordt het uitvoer bestand anders behandeld dan onder de normale werking\&. Het mag bevatten een
\fBprintf\fR
zoals uitgedrukt \*(Aq%d\*(Aq inclusief een optioneel veld, b\&.v\&. \*(Aq%02d\*(Aq\&. Indien dit het geval is, zal het huidige bestandsaantal geschikt worden geformatteerd en op dat punt in de bestandsnaam worden ingevoegd\&. Is er geen dergelijk patroon dan wordt een patroon van \*(Aq\-%03d\*(Aq aangenomen direct voor de bestand extensie: \*(Aq\-o output\&.mkv\*(Aq zou resulteren in \*(Aqoutput\-001\&.mkv\*(Aq en zo verder\&. Is er geen extensie dan zal \*(Aq\-%03d\*(Aq worden toegevoegd aan de naam\&.
.RE
.PP
\fB\-\-link\fR
.RS 4
Bestanden linken aan een ander tijdens het splitsen van het uitvoer bestand\&. Zie de sectie over:
Bestand linken
onderstaand voor details\&.
.RE
.PP
\fB\-\-link\-to\-previous\fR \fIsegment\-UID\fR
.RS 4
Verbindt het laatste uitvoerbestand met het segment UID ingegeven door
\fIsegment\-UID\fR
parameter\&. Zie de sectie over:
Bestand linken
onderstaand voor details\&.
.RE
.PP
\fB\-\-link\-to\-next\fR \fIsegment\-UID\fR
.RS 4
Verbindt het laatste uitvoerbestand met het segment UID ingegeven door
\fIsegment\-UID\fR
parameter\&. Zie de sectie over:
Bestand linken
onderstaand voor details\&.
.RE
.PP
\fB\-\-append\-mode\fR \fImode\fR
.RS 4
Calculeert hoe tijd codes worden berekend wanneer die worden toegevoegd aan een bestand\&. De parameter
\fImode\fR
kan twee waardes bevatten: \*(Aqfile\*(Aq welke ook standaard is en \*(Aqtrack\*(Aq\&.
.sp
Wanneer mkvmerge een spoor toevoegt (genoemd \*(Aqtrack2_1\*(Aq vanaf nu) van een tweede bestand (genoemd \*(Aqfile2\*(Aq) naar een spoor (genoemd \*(Aqtrack1_1\*(Aq) van het eerste bestand (genoemd \*(Aqfile1\*(Aq) dan moet het alle tijd codes compenseren voor \*(Aqtrack2_1\*(Aq met een bepaalde hoeveelheid\&. Voor \*(Aqfile\*(Aq mode is deze hoeveelheid de hoogste tegengekomen tijd code in \*(Aqfile1\*(Aq\&. zelfs wanneer die tijd code van een ander spoor is dan \*(Aqtrack1_1\*(Aq\&. In spoor mode de is compensatie de hoogste tijd code van \*(Aqtrack1_1\*(Aq\&.
.sp
Helaas kan mkvmerge niet detecteren welke mode betrouwbaar is\&. Daarom zet het de standaard waarde naar \*(Aqfile\*(Aq mode\&. \*(Aqfile\*(Aq mode werkt gewoonlijk beter voor bestanden indien die onafhankelijk van elkaar werden gemaakt; b\&.v\&. het toevoegen van
AVI
of
MP4
bestanden\&. \*(Aqtrack\*(Aq mode zou beter werken voor bronnen die hoofdzakelijk een deel van \('e\('en groot bestand zijn, b\&.v\&. voor
VOB
en
EVO
bestanden\&.
.sp
Hoofdstuk sporen worden altijd behandeld alsof \*(Aqfile\*(Aq mode actief is en zelfs wanneer \*(Aqtrack\*(Aq mode actueel is\&.
.RE
.PP
\fB\-\-append\-to\fR \fISFID1:STID1:DFID1:DTID1\fR\fI[,\&.\&.\&.]\fR
.RS 4
Deze optie controleert welk spoor aan welk ander spoor moet worden toegevoegd (bestand wordt dubbel zo groot)\&. Elke specificatie bevat vier ID\*(Aqs: een bestand ID, een spoor ID, een tweede bestand ID en een tweede spoor ID\&. Het eerste paar, "source file ID" en "source track ID", identificeert het spoor dat moet worden toegevoegd\&. Het tweede paar, "destination file ID" en "destination track ID", identificeert het spoor waaraan de eerste is toegevoegd\&.
.sp
Als deze optie weggelaten wordt dan wordt een standaard indeling gebruikt\&. Deze standaard indeling voegt elk spoor van het huidige bestand toe aan een spoor van het vorige bestand met hetzelfde spoor ID\&. Dit staat het makkelijk toevoegen toe indien een film gesplitst is in twee delen en beide bestanden dezelfde aantal sporen en spoor ID\*(Aqs hebben, met het commando
\fBmkvmerge \-o output\&.mkv part1\&.mkv +part2\&.mkv\fR\&.
.RE
.PP
\fB+\fR
.RS 4
Een enkele \*(Aq+\*(Aq veroorzaakt dat het volgende bestand wordt bijgevoegd (bestand wordt dubbel zo groot) i\&.p\&.v\&. toegevoegd\&. De \*(Aq+\*(Aq kan worden ingegeven voor elk volgende bestandsnaam\&. Daarom zijn de volgende twee commando\*(Aqs gelijkwaardig:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o full\&.mkv file1\&.mkv + file2\&.mkv
$ mkvmerge \-o full\&.mkv file1\&.mkv +file2\&.mkv
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB=\fR
.RS 4
Normaal kijkt
\fBmkvmerge\fR(1)
naar bestanden in dezelfde map welke dezelfde basis naam bevatten maar alleen verschillen van volgordenummer (b\&.v\&. \*(AqVTS_01_1\&.VOB\*(Aq, \*(AqVTS_01_2\&.VOB\*(Aq, \*(AqVTS_01_3\&.VOB\*(Aq etc\&.) en behandelt al die bestanden alsof zij \('e\('en groot bestand waren\&. Deze optie, een enkele \*(Aq=\*(Aq maakt dat mkvmerge niet kijkt naar die extra bestanden\&.
.sp
De \*(Aq=\*(Aq kan ook worden ingegeven voor elk volgende bestandsnaam\&. Daarom zijn de volgende twee commando\*(Aqs gelijkwaardig:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o full\&.mkv = file1\&.mkv
$ mkvmerge \-o full\&.mkv =file1\&.mkv
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB(\fR \fIfile1\fR \fIfile2\fR \fB)\fR
.RS 4
Als er meerdere bestandsnamen zijn opgenomen tussen haakjes, dan zullen die bestanden worden behandeld alsof ze zijn samengevoegd tot \('e\('en enkel groot bestand, dat bestaat uit de inhoud van elk van de bestanden achter elkaar\&.
.sp
Dit kan gebruikt worden voor b\&.v\&. VOB bestanden vanaf een DVD of MPEG transport stromen\&. Het kan niet worden gebruikt als elk bestand zijn eigen set koppen bevat wat meestal het geval is bij stand\-alone\-bestanden, zoals AVI of MP4\&.
.sp
Een bestandsnaam tussen haakjes te zetten voorkomt tevens dat
\fBmkvmerge\fR(1)
kijkt naar extra bestanden met dezelfde naam zoals beschreven in
option \fB=\fR\&. Daarom zijn deze twee commando\*(Aqs gelijkwaardig:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o out\&.mkv = file\&.mkv
$ mkvmerge \-o out\&.mkv \*(Aq(\*(Aq file\&.mkv \*(Aq)\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Verschillende dingen dienen te worden opgemerkt:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Er moet een spatie zijn zowel voor als na het open en sluit haken\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Elke parameter tussen haakjes wordt ge\(:interpreteerd als een bestandsnaam\&. Daarom moeten alle opties die van toepassing zijn op dit logische bestand opgenomen moet worden voor de openende haakjes\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Sommige insluitingen worden behandeld als speciale tekens\&. Vandaar dat je moet insluiten of citeren ze zoals in het voorbeeld hierboven\&.
.RE
.RE
.SS "Bijlage ondersteuning (meer globale opties)"
.PP
\fB\-\-attachment\-description\fR \fIdescription\fR
.RS 4
Normale tekst beschrijving van de volgende bijlage\&. Is van toepassing op de volgende
\fB\-\-attach\-file\fR
of
\fB\-\-attach\-file\-once\fR
optie\&.
.RE
.PP
\fB\-\-attachment\-mime\-type\fR \fIMIME type\fR
.RS 4

MIME
type van de volgende bijlage\&. Is van toepassing op de volgende
\fB\-\-attach\-file\fR
of
\fB\-\-attach\-file\-once\fR
optie\&. Een lijst van offici\(:ele herkende
MIME
typen kan gevonden worden b\&.v\&. op de
\m[blue]\fBIANA\fR\m[]\&\s-2\u[2]\d\s+2
thuisbasis\&. Het
MIME
type is verplicht voor een bijlage\&.
.RE
.PP
\fB\-\-attachment\-name\fR \fIname\fR
.RS 4
Stelt de naam in voor deze bijlage welke wordt opgeslagen in het uitvoer bestand\&. Als deze optie niet is opgegeven dan zal de naam worden afgeleid van de naam van de bijlage zoals gegeven met de
\fB\-\-attach\-file\fR
of de
\fB\-\-attach\-file\-once\fR
optie\&.
.RE
.PP
\fB\-\-attach\-file\fR \fIfile\-name\fR, \fB\-\-attach\-file\-once\fR \fIfile\-name\fR
.RS 4
Cre\(:eert een bestandsbijlage binnenin het
Matroska(TM)
bestand\&. Het
MIME
type moet ingesteld zijn voordat deze optie gebruikt kan worden\&. Het verschil tussen deze twee vormen is, dat tijdens het splitsen van de bestanden vastgemaakt met
\fB\-\-attach\-file\fR
aan alle uitvoerbestanden zijn vastgemaakt terwijl degene vastgemaakt met de
\fB\-\-attach\-file\-once\fR
alleen zijn vastgemaakt aan het eerste bestand\&. Is splitsen niet gebruikt dan doen beide hetzelfde\&.
.sp

\fBmkvextract\fR(1)
kan worden gebruikt om bestanden uit een
Matroska(TM)
bestand te halen\&.
.RE
.SS "Opties welke gebruikt kunnen worden voor elk invoer bestand"
.PP
\fB\-a\fR, \fB\-\-audio\-tracks\fR \fI[!]\fR\fIn,m,\&.\&.\&.\fR
.RS 4
Kopieer de audio sporen
\fIn\fR,
\fIm\fR
etc\&. De nummers zijn track ID\*(Aqs welke verkregen kunnen worden met de
\fB\-\-identify\fR
schakelaar\&. Zij zijn simpelweg niet de spoor nummers (zie sectie
Spoor ID's)\&. Standaard: Kopieer alle audio sporen\&.
.sp
Als de IDs zijn voorgezet met
!
dan is de betekenis omgekeerd: kopieer alles maar de ID\*(Aqs lijsten na de
!\&.
.RE
.PP
\fB\-d\fR, \fB\-\-video\-tracks\fR \fI[!]\fR\fIn,m,\&.\&.\&.\fR
.RS 4
Kopieer de video sporen
\fIn\fR,
\fIm\fR
etc\&. De nummers zijn track ID\*(Aqs welke kunnen worden verkregen met de
\fB\-\-identify\fR
schakelaar\&. Zij zijn simpelweg niet de spoor nummers (zie sectie
Spoor ID's)\&. Standaard: Kopieer alle video sporen\&.\&.
.sp
Als de IDs zijn voorgezet met
!
dan is de betekenis omgekeerd: kopieer alles maar de ID\*(Aqs lijsten na de
!\&.
.RE
.PP
\fB\-s\fR, \fB\-\-subtitle\-tracks\fR \fI[!]\fR\fIn,m,\&.\&.\&.\fR
.RS 4
Kopieer de ondertitel sporen
\fIn\fR,
\fIm\fR
etc\&. De nummers zijn track ID\*(Aqs welke kunnen worden verkregen met de
\fB\-\-identify\fR
schakelaar\&. Zij zijn simpelweg niet de spoor nummers (zie sectie
Spoor ID's)\&. Standaard: Kopieer alle ondertitel sporen\&.
.sp
Als de IDs zijn voorgezet met
!
dan is de betekenis omgekeerd: kopieer alles maar de ID\*(Aqs lijsten na de
!\&.
.RE
.PP
\fB\-b\fR, \fB\-\-button\-tracks\fR \fI[!]\fR\fIn,m,\&.\&.\&.\fR
.RS 4
Kopieer de knop sporen
\fIn\fR,
\fIm\fR
etc\&. De nummers zijn track ID\*(Aqs welke kunnen worden verkregen met de
\fB\-\-identify\fR
schakelaar\&. Zij zijn simpelweg niet de spoor nummers (zie sectie
Spoor ID's)\&. Standaard: Kopieer alle knop sporen\&.
.sp
Als de IDs zijn voorgezet met
!
dan is de betekenis omgekeerd: kopieer alles maar de ID\*(Aqs lijsten na de
!\&.
.RE
.PP
\fB\-\-track\-tags\fR \fI[!]\fR\fIn,m,\&.\&.\&.\fR
.RS 4
Kopieer de markeringen voor sporen
\fIn\fR,
\fIm\fR
etc\&. De nummers zijn track ID\*(Aqs welke kunnen worden verkregen met de
\fB\-\-identify\fR
schakelaar (zie sectie
Spoor ID's)\&. Zij zijn simpelweg niet de spoor nummers\&. Standaard: Kopieer alle markering sporen\&.
.sp
Als de IDs zijn voorgezet met
!
dan is de betekenis omgekeerd: kopieer alles maar de ID\*(Aqs lijsten na de
!\&.
.RE
.PP
\fB\-m\fR, \fB\-\-attachments\fR \fI[!]\fR\fIn\fR\fI[:all|first]\fR\fI,m\fR\fI[:all|first]\fR\fI,\&.\&.\&.\fR
.RS 4
Kopieer de bijlagen met de ID\*(Aqs
\fIn\fR,
\fIm\fR
etc\&. naar allen of alleen het eerste uitvoer bestand\&. Elk ID kan opgevolgd worden door \*(Aq:all\*(Aq (welke standaard is, als geen van twee is opgegeven) of \*(Aq:first\*(Aq\&. Als het splitsen actief is, dan zullen die bijlagen waarvan de ID\*(Aqs zijn gespecificeerd met \*(Aq:all\*(Aq worden gekopieerd naar alle resulterende uitvoer bestanden, terwijl de anderen alleen gekopieerd worden naar het eerste uitvoerbestand\&. Als splitsen niet actief is, dan hebben beide varianten hetzelfde effect\&.
.sp
Standaard is, kopieer alle bijlagen naar alle uitvoer bestanden\&.
.sp
Als de IDs zijn voorgezet met
!
dan is de betekenis omgekeerd: kopieer alles maar de ID\*(Aqs lijsten na de
!\&.
.RE
.PP
\fB\-A\fR, \fB\-\-no\-audio\fR
.RS 4
Kopieer geen enkel audio spoor van dit bestand\&.
.RE
.PP
\fB\-D\fR, \fB\-\-no\-video\fR
.RS 4
Kopieer geen enkel video spoor van dit bestand\&.
.RE
.PP
\fB\-S\fR, \fB\-\-no\-subtitles\fR
.RS 4
Kopieer geen enkel ondertitel spoor van dit bestand\&.
.RE
.PP
\fB\-B\fR, \fB\-\-no\-buttons\fR
.RS 4
Kopieer geen enkel knop spoor van dit bestand\&.
.RE
.PP
\fB\-T\fR, \fB\-\-no\-track\-tags\fR
.RS 4
Kopieer geen enkel spoor\-specifieke markeringen van dit bestand\&.
.RE
.PP
\fB\-\-no\-chapters\fR
.RS 4
Kopieer geen hoofdstukken van dit bestand\&.
.RE
.PP
\fB\-M\fR, \fB\-\-no\-attachments\fR
.RS 4
Kopieer geen bijlagen van dit bestand\&.
.RE
.PP
\fB\-\-no\-global\-tags\fR
.RS 4
Kopieer geen globale markeringen van dit bestand\&.
.RE
.PP
\fB\-\-chapter\-charset\fR \fIcharacter\-set\fR
.RS 4
Stelt het karakter set in, die gebruikt wordt voor de conversie naar UTF\-8 voor het hoofdstuk informatie die zich bevindt in het bronbestand\&. Zie de sectie over:
Tekst bestanden en karakter set conversies
voor een uitleg hoe
\fBmkvmerge\fR(1)
converteert tussen de karakter sets\&.
.RE
.PP
\fB\-\-chapter\-language\fR \fIlanguage\-code\fR
.RS 4
Zet de ISO639\-2 taal code, welke wordt geschreven voor elk hoofdstuk ingang\&. Deze optie kan gebruikt worden, voor bronbestanden welke hoofdstuk informatie bevatten maar g\('e\('en informatie over de talen, b\&.v\&. voor MP4 en OGM bestanden\&.
.RE
.PP
\fB\-y\fR, \fB\-\-sync\fR \fITID:d\fR\fI[,o[/p]]\fR
.RS 4
Stelt de tijd codes bij van het spoor met het id
\fITID\fR
met
\fId\fR
ms\&. De spoor ID\*(Aqs zijn hetzelfde als degene gegeven met
\fB\-\-identify\fR
(zie sectie
Spoor ID's)\&.
.sp

\fIo\fR/\fIp\fR: Stel de tijd codes bij met
\fIo\fR/\fIp\fR
om lineaire driften te corrigeren\&.
\fIp\fR
standaard naar 1 indien weggelaten\&. Beide
\fIo\fR
en
\fIp\fR
kunnen een veranderbaar nummer zijn\&.
.sp
Standaard: geen handmatige sync correctie (wat hetzelfde is als
\fId\fR
=
\fB0\fR
en
\fIo\fR/\fIp\fR
=
\fB1\&.0\fR)\&.
.sp
Deze optie kan meerdere keren worden gebruikt voor een invoer bestand, is van toepassing op verschillende sporen door het spoor ID elke keer te selecteren\&.
.RE
.PP
\fB\-\-cues\fR \fITID:none|iframes|all\fR
.RS 4
Controle voor welke sporen cue (index) ingangen worden gecre\(:eerd voor een opgegeven spoor (zie sectie
Spoor ID's)\&. \*(Aqnone\*(Aq remt het cre\(:eren van volg document(en) (cue) af\&. Voor \*(Aqiframes\*(Aq all\('e\('en blokken zonder voor of achteruit referenties ( = I beelden in video sporen) worden ingevoerd in het \*(Aqvolg document(en) (cue)\*(Aq\&. \*(Aqall\*(Aq zorgt ervoor dat
\fBmkvmerge\fR(1)
aanmaakt, volg document(en) (cue) voor alle blokken welke het bestand erg groot maakt\&.
.sp
Standaard is \*(Aqiframes\*(Aq voor video sporen en \*(Aqnone\*(Aq voor alle anderen\&. Zie ook opties
\fB\-\-no\-cues\fR
welke verwezenlijken het cre\(:eren van volg document(en) (cue) ongeacht de
\fB\-\-cues\fR
gebruikte opties\&.
.sp
Deze optie kan meerdere keren worden gebruikt voor een invoer bestand, is van toepassing op verschillende sporen door het spoor ID elke keer te selecteren\&.
.RE
.PP
\fB\-\-default\-track\fR \fITID\fR\fI[:bool]\fR
.RS 4
Zet de \*(Aqstandaard\*(Aq markering voor een gegeven spoor (zie sectie
Spoor ID's) als het optionele argument
\fIbool\fR
niet aanwezig is\&. Als de gebruiker niet zelf uitdrukkelijk een spoor selecteert, dan zou de af speler een spoor prefereren dat zijn \*(Aqstandaard\*(Aq markering heeft\&. Alleen \('e\('en spoor van elk soort (audio, video, ondertitels, knoppen) kunnen deze \*(Aqstandaard\*(Aq markering gezet hebben\&. Indien een gebruiker geen spoor wenst te hebben met een standaard spoor markering gezet, dan moet hij zetten
\fIbool\fR
naar
\fB0\fR
voor alle sporen\&.
.sp
Deze optie kan meerdere keren worden gebruikt voor een invoer bestand, is van toepassing op verschillende sporen door het spoor ID elke keer te selecteren\&.
.RE
.PP
\fB\-\-forced\-track\fR \fITID\fR\fI[:bool]\fR
.RS 4
Stelt de \*(Aqgeforceerde\*(Aq markering in voor een gegeven spoor (zie sectie
Spoor ID's) als het optionele argument
\fIbool\fR
niet aanwezig is\&. Een af speler moet alle sporen afspelen waarvan deze markering is gezet
\fB1\fR\&.
.sp
Deze optie kan meerdere keren worden gebruikt voor een invoer bestand, is van toepassing op verschillende sporen door het spoor ID elke keer te selecteren\&.
.RE
.PP
\fB\-\-blockadd\fR \fITID:level\fR
.RS 4
Houd alleen de
BlockAdditions
tot aan niveau
\fIlevel\fR
voor het opgegeven spoor\&. Standaard is alle niveaus\&. Deze optie heeft alleen effect op sommige codecs zoals WAVPACK4\&.
.RE
.PP
\fB\-\-track\-name\fR \fITID:name\fR
.RS 4
Stelt het spoor naam in van een gegeven spoor (zie sectie
Spoor ID's) naar
\fInaam\fR\&.
.RE
.PP
\fB\-\-language\fR \fITID:language\fR
.RS 4
Stelt de taal in voor het opgegeven spoor (zie sectie
Spoor ID's)\&. Beide ISO639\-2 taal codes en ISO639\-1 land codes zijn toegestaan\&. Het land code wordt automatisch vertaald naar taal code\&. Alle talen inclusief hun ISO639\-2 codes kunnen uit gelijst worden met
\fB\-\-list\-languages\fR
optie\&.
.sp
Deze optie kan meerdere keren worden gebruikt voor een invoer bestand, is van toepassing op verschillende sporen door het spoor ID elke keer te selecteren\&.
.RE
.PP
\fB\-t\fR, \fB\-\-tags\fR \fITID:file\-name\fR
.RS 4
Leest de markeringen in van het spoor met het nummer
\fITID\fR
van de bestand
\fIfile\-name\fR\&. Zie de sectie over:
Markeringen
hieronder voor details\&.
.RE
.PP
\fB\-\-aac\-is\-sbr\fR \fITID\fR\fI[:0|1]\fR
.RS 4
Vertelt
\fBmkvmerge\fR(1)
dat het spoor met het ID
\fITID\fR
een
SBR AAC
is (ook bekend als
HE\-AAC
of een
AAC+)\&. Deze optie is nodig als a) een bron bestand een
AAC
bestand is (\fIniet\fR
voor een
Matroska(TM)
bestand) en b) het
AAC
bestand bevat
SBR AAC
data\&. De reden voor deze schakelaar is, dat het normaal technisch niet mogelijk is, automatisch te vertellen dat
AAC
data van
SBR AAC
data zonder deze volledig te decoderen van een
AAC
beeld\&. Aangezien er verscheidene octrooi/patent kwesties zijn met
AAC
decoders zal
\fBmkvmerge\fR(1)
nooit dit decodeer stadium bevatten\&. Dus voor
SBR AAC
bestanden is deze schakelaar een vereiste\&. Het resulterende bestand zou niet correct afgespeeld kunnen worden of zelfs helemaal niet, wanneer deze schakelaar werd weggelaten\&.
.sp
Als het bron bestand een
Matroska(TM)
bestand is, dan zou de
CodecID
genoeg moeten zijn om deze
SBR AAC
te detecteren\&. Hoewel, als de
CodecID
verkeerd is, dan kan deze schakelaar gebruikt worden om dat te corrigeren\&.
.sp
Als mkvmerge verkeerd detecteert dat een
AAC
bestand een
SBR
is, dan kan je toevoegen \*(Aq:0\*(Aq aan het spoor ID\&.
.RE
.PP
\fB\-\-timecodes\fR \fITID:file\-name\fR
.RS 4
Leest de te gebruiken tijd codes in voor een specifiek spoor ID van
\fIfile\-name\fR\&. Deze krachtige tijd codes heffen de tijd codes die
\fBmkvmerge\fR(1)
normaal berekend op\&. Lees de sectie over:
Externe tijd code bestanden\&.
.RE
.PP
\fB\-\-default\-duration\fR \fITID:x\fR
.RS 4
Forceert de standaard duur van een gegeven spoor naar de gegeven waarde\&. Tevens de spoor tijd code aanpast zodat die overeenkomt met de standaard duur\&. Het argument
\fIx\fR
moet zijn vastgezet met \*(Aqs\*(Aq, \*(Aqms\*(Aq, \*(Aqus\*(Aq, \*(Aqns\*(Aq of \*(Aqfps\*(Aq \*(Aqp\*(Aq of \*(Aqi
om te specificeren de standaard duur in seconden, milliseconden, microseconden, nanoseconden of respectievelijk de \*(Aq\*(Aqbeelden per seconde\*(Aq (fps)\&. Het aantal
\fIx\fR
kan zelf een veranderbaar nummer zijn of een fractie\&.
.sp
Als de standaard duur niet is geforceerd dan zal mkvmerge proberen de spoor standaard duur proberen te verkrijgen uit de inhoud en/of de gecodeerde bit stroom voor bepaalde spoortypen, b\&.v\&. AVC/h\&.264 of MPEG\-2\&.
.sp
Deze optie kan ook gebruikt worden om de
FPS
(beelden per seconde) te veranderen van video sporen zonder een extern tijd code bestand te hoeven gebruiken\&.
.RE
.PP
\fB\-\-nalu\-size\-length\fR \fITID:n\fR
.RS 4
Forceert de
NALU
lengte grootte naar
\fIn\fR
bytes\&. Deze parameter wordt alleen gebruikt als de
AVC/h\&.264
elementaire stroom inpakker is gebruikt\&. Indien weggelaten is de standaard waarde 4 bytes, maar er zijn bestanden die beelden of delen bevatten die kleiner zijn dan 65536 bytes\&. Voor dergelijke bestanden kan je deze parameter gebruiken en de grootte verminderen naar 2\&.
.RE
.PP
\fB\-\-compression\fR \fITID:n\fR
.RS 4
Selecteert de te gebruiken compressie methode in voor het spoor\&. Opmerking: de af speler dient deze methode ook te ondersteunen\&. Geldige waarden zijn \*(Aqnone\*(Aq, \*(Aqzlib\*(Aq, \*(Aqlzo\*(Aq/\*(Aqlxo1x\*(Aq, \*(Aqbz2\*(Aq/\*(Aqbzlib\*(Aq en \*(Aqmpeg4_p2\*(Aq/\*(Aqmpeg4p2\*(Aq\&. De waarden \*(Aqlzo\*(Aq/\*(Aqlxo1x\*(Aq en \*(Aqbz2\*(Aq/\*(Aqbzlib\*(Aq zijn all\('e\('en beschikbaar als
\fBmkvmerge\fR(1)
is gecompileerd met de ondersteuning voor de
liblzo(TM)
respectievelijk
bzlib(TM)
compressie bibliotheken\&.
.sp
De compressie methode \*(Aqmpeg4_p2\*(Aq/\*(Aqmpeg4p2\*(Aq is een speciale compressie methode genoemd \*(Aqheader removal\*(Aq die is all\('e\('en beschikbaar voorMPEG4
deel 2 video sporen\&.
.sp
Standaard voor sommige ondertitels zijn \*(Aqzlib\*(Aq compressie\&. Deze compressie wordt door bijna alle af spelers ondersteund zo niet allen\&. Ondersteuning voor andere compressie methoden anders dan \*(Aqnone\*(Aq is niet verzekerd\&.
.RE
.SS "Opties die alleen op video sporen van toepassing zijn"
.PP
\fB\-f\fR, \fB\-\-fourcc\fR \fITID:FourCC\fR
.RS 4
Forceert de
FourCC
naar de opgegeven waarde\&. Werkt all\('e\('en voor video sporen in de \*(AqMS verenigbare mode\*(Aq\&.
.RE
.PP
\fB\-\-display\-dimensions\fR \fITID:widthxheight\fR
.RS 4

Matroska(TM)
bestanden bevatten twee waarden die het scherm eigenschappen instelt waarnaar een af speler met afspelen naar toe zou moeten schalen: scherm breedte en scherm hoogte\&. Deze waarden worden ingesteld met deze optie, b\&.v\&. \*(Aq1:640x480\*(Aq\&.
.sp
Een andere manier om de te gebruiken waarden te specificeren is
\fB\-\-aspect\-ratio\fR
of de
\fB\-\-aspect\-ratio\-factor\fR
optie (zie hieronder)\&. Deze opties zijn wederzijds \- exclusief\&.
.RE
.PP
\fB\-\-aspect\-ratio\fR \fITID:ratio|width/height\fR
.RS 4

Matroska(TM)
bestanden bevatten twee waarden die de scherm eigenschappen instelt waarnaar een af speler met afspelen naar toe zou moeten schalen: scherm breedte en scherm hoogte\&. Met deze optie zal
\fBmkvmerge\fR(1)
automatisch calculeren het scherm breedte en het scherm hoogte gebaseerd, op de originele beelden/plaatjes breedte en hoogte en de opgegeven verwachte verhouding met deze optie\&. De verhouding kan \('e\('en van beiden zijn een veranderbaar nummer
\fIverhouding\fR
of als een fractie \*(Aq\fIbreedte\fR/\fIhoogte\fR\*(Aq, b\&.v\&. \*(Aq16/9\*(Aq\&.
.sp
Een andere manier om de te gebruiken waarden te specificeren is
\fB\-\-aspect\-ratio\-factor\fR
of
\fB\-\-display\-dimensions\fR
opties (zie hieronder en hierboven)\&. Deze opties zijn wederzijds \- exclusief\&.
.RE
.PP
\fB\-\-aspect\-ratio\-factor\fR \fITID:factor|n/d\fR
.RS 4
Een andere manier om de verwachtte verhouding te specificeren is een
\fIfactor\fR\&. De originele verwachtte verhouding factor wordt eerst vermenigvuldigd met deze
\fIfactor\fR
en daarna gebruikt als doel verhouding\&.
.sp
Een andere manier om de te gebruiken waarden te specificeren is
\fB\-\-aspect\-ratio\fR
of
\fB\-\-display\-dimensions\fR
opties (zie boven)\&. Deze opties zijn wederzijds \- exclusief\&.
.RE
.PP
\fB\-\-cropping\fR \fITID:left,top,right,bottom\fR
.RS 4
Stelt de video spoor uitsnij parameters in naar een gegeven waarde\&.
.RE
.PP
\fB\-\-stereo\-mode\fR \fITID:n|keyword\fR
.RS 4
Stelt de video mode in voor het video spoor met het spoor ID
\fITID\fR\&. Deze mode kan zijn een nummer
\fIn\fR
tussen
\fB0\fR
en
\fB14\fR
of \('e\('en van de volgende:
.sp
\*(Aqmono\*(Aq, \*(Aqside_by_side_left_first\*(Aq, \*(Aqtop_bottom_right_first\*(Aq, \*(Aqtop_bottom_left_first\*(Aq, \*(Aqcheckerboard_right_first\*(Aq, \*(Aqcheckerboard_left_first\*(Aq, \*(Aqrow_interleaved_right_first\*(Aq, \*(Aqrow_interleaved_left_first\*(Aq, \*(Aqcolumn_interleaved_right_first\*(Aq, \*(Aqcolumn_interleaved_left_first\*(Aq, \*(Aqanaglyph_cyan_red\*(Aq, \*(Aqside_by_side_right_first\*(Aq, \*(Aqanaglyph_green_magenta\*(Aq, \*(Aqboth_eyes_laced_left_first\*(Aq, \*(Aqboth_eyes_laced_right_first\*(Aq\&.
.RE
.SS "Opties alleen geldig voor tekst ondertitel sporen"
.PP
\fB\-\-sub\-charset\fR \fITID:character\-set\fR
.RS 4
Stelt het karakter set conversie in naar UTF\-8 voor UTF\-8 ondertitels van een opgegeven spoor ID\&. Indien niet opgegeven, dan worden het huidig verkregen besturingssysteem locatie gebruikt\&. Opmerking: een karakter set voor ondertitels is niet nodig wanneer er gelezen wordt vanuit een
Matroska(TM)
bestand of van Kate stromen, omdat deze altijd zijn opgeslagen in het UTF\-8 format\&. Zie de sectie over:
Tekst bestanden en karakter set conversies
voor een uitleg hoe
\fBmkvmerge\fR(1)
converteert tussen het verschillende karakter sets\&.
.sp
Deze optie kan meerdere keren worden gebruikt voor een invoer bestand, is van toepassing op verschillende sporen door het spoor ID elke keer te selecteren\&.
.RE
.SS "Andere opties"
.PP
\fB\-i\fR, \fB\-\-identify\fR \fIfile\-name\fR
.RS 4
Zal
\fBmkvmerge\fR(1)
(met een sonde) een enkel bestand aftasten en het type rapporteren, de sporen in het bestand en hun spoor ID\*(Aqs\&. Als deze optie wordt gebruikt dan is de enige andere toegestane optie de bestandsnaam\&.
.RE
.PP
\fB\-I\fR, \fB\-\-identify\-verbose\fR \fIfile\-name\fR
.RS 4
Zal
\fBmkvmerge\fR(1)
(met een sonde) een enkel bestand aftasten en het type rapporteren, de sporen in het bestand en hun spoor ID\*(Aqs\&. Als deze optie wordt gebruikt dan is de enige andere toegestane optie de bestandsnaam\&.
.sp
Deze optie maakt dat
\fBmkvmerge\fR(1)
extra informatie uitvoert over de inhoud en elk spoor\&. De extra informatie staat tussen haken ( [] )\&. Het bevat een spatie gescheiden sleutel/waarde paar, waar de sleutel en waardes zijn gescheiden door een dubbel punt (:)\&.
.sp
Elke waarde wordt overgeslagen conform de regels beschreven in de sectie over:
Overslaan van speciale karakter(s) in tekst\&.
.RE
.PP
\fB\-l\fR, \fB\-\-list\-types\fR
.RS 4
Somt invoer bestandstypen op\&.
.RE
.PP
\fB\-\-list\-languages\fR
.RS 4
Somt alle talen en hun ISO639\-2 codes op welke gebruikt kunnen worden met de
\fB\-\-language\fR
optie\&.
.RE
.PP
\fB\-\-priority\fR \fIpriority\fR
.RS 4
Stelt het proces prioriteit in waarmee
\fBmkvmerge\fR(1)
zijn werk doet\&. Geldige waarden zijn \*(Aqlowest\*(Aq, \*(Aqlower\*(Aq, \*(Aqnormal\*(Aq, \*(Aqhigher\*(Aq en \*(Aqhighest\*(Aq\&. Is niets ingegeven dan wordt \*(Aqnormal\*(Aq gebruikt\&. Op unix achtige systemen zal
\fBmkvmerge\fR(1)
gebruiken de
\fBnice\fR(2)
functie\&. Daarom kan all\('e\('en de \*(Aqsuper\*(Aq gebruiker die gebruiken \*(Aqhigher\*(Aq en \*(Aqhighest\*(Aq\&. Op Windows zijn alle waarden voor iedereen beschikbaar\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fI(karakterset)\fR
.RS 4
Plaatst het karakter dat wordt geplaatst om de reeksen om te zetten die op de commandoregel worden ingeven\&. Het is standaard aan het karakter van het systeem en afhankelijk van het besturingssysteem locatie\&. Deze instellingen zijn van toepassing op argumenten van de volgende opties:
\fB\-\-title\fR,
\fB\-\-track\-name\fR
en
\fB\-\-attachment\-description\fR\&.
.RE
.PP
\fB\-\-output\-charset\fR \fI(karakterset)\fR
.RS 4
Stelt het karakter set in, waarnaar de reeksen naar de uitvoer dienen te worden geconverteerd\&. Standaard wordt gebruikt het karakter set die afhankelijk is van wat er in uw besturingssysteem staat aangegeven (locatie)\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fI(bestandsnaam)\fR
.RS 4
Schrijft alle berichten naar een bestand
\fIfile\-name\fR
i\&.p\&.v\&. naar de \*(Aqapparaat/houder\*(Aq\&. Terwijl dit gemakkelijk met uitvoer omleiden kan worden gedaan er zijn gevallen waarin deze optie nodig is: wanneer de verwerker e\&.e\&.a\&. herinterpreteert voordat het geschreven wordt naar de uitvoer bestand\&. Het karakter set met
\fB\-\-output\-charset\fR
is toegewezen\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIcode\fR
.RS 4
Forceert de vertaling voor de te gebruiken taal
\fIcode\fR
(b\&.v\&. \*(Aqde_DE\*(Aq voor de Duitse taal)\&. Het heeft de voorkeur de \*(Aqomgevingsvariabelen\*(Aq te gebruiken
\fILANG\fR,
\fILC_MESSAGES\fR
en
\fILC_ALL\fR
Hoewel opvragen van een \*(Aqlist\*(Aq voor een land
\fIcode\fR
zal er voor zorgen dat
\fBmkvextract\fR(1)
een lijst zal uitvoeren van alle beschikbare vertalingen\&.
.RE
.PP
\fB\-\-title\fR \fIonderwerp\fR
.RS 4
Zet debuggen aan voor een specifieke mogelijkheid\&. Dit is alleen zinvol voor ontwikkelaars\&.
.RE
.PP
\fB\-\-tags\fR \fIfeature\fR
.RS 4
Zet experimentele mogelijkheden aan\&. Een lijst van beschikbare mogelijkheden kan worden opgevraagd met
\fBmkvmerge \-\-engage list\fR\&. Deze mogelijkheden zijn niet bedoeld in normale situaties\&.
.RE
.PP
\fB@\fR\fIoptions\-file\fR
.RS 4
Leest extra commandoregel informatie uit een bestand
\fIoptions\-file\fR\&. Zie de sectie over:
Optie bestanden
voor meer informatie\&.
.RE
.PP
\fB\-\-capabilities\fR
.RS 4
Somt informatie op over optionele mogelijkheden die zijn gecompileerd en sluit af\&. De eerste uitvoer regel zal de versie informatie zijn\&. Alle volgende informatie regels bevatten exact \('e\('en woord, waarvan de aanwezigheid aangeeft welke eigenschapen er binnenin zijn gecompileerd\&. Deze mogelijkheden zijn:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\*(AqBZ2\*(Aq \-\- de
bzlib(TM)
compressie bibliotheek\&. Heeft effect op de beschikbare compressie methoden voor de
\fB\-\-compression\fR
optie\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\*(AqLZO\*(Aq \-\- de
lzo(TM)
compressie bibliotheek\&. Heeft effect op de beschikbare compressie methoden voor de
\fB\-\-compression\fR
optie\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\*(AqFLAC\*(Aq \-\- lezen raw
FLAC
bestanden en behandelen van
FLAC
sporen in andere inhoudsmaten, b\&.v\&.
Ogg(TM)
of
Matroska(TM)\&.
.RE
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Toon gebruik informatie en sluit af\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Toon versie informatie en sluit af\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Controleert online op nieuwere versies via ophalen op adres
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Vier regels worden uitgevoerd in
key=value
stijl: het adres van waar de informatie wordt verkregen (key
version_check_url), de huidig uitgevoerde versie (key
running_version), laatst uitgebrachte versie (key
available_version
en het ophaal adres (key
download_url)\&.
.sp
Nadien sluit het programma af met een afsluitwaarde van 0 als er geen nieuwere versie beschikbaar is, met een 1 als er een nieuwere beschikbaar is en 2 indien er een fout ontstond (b\&.v\&. als de opwaardeer informatie niet verkregen kon worden)\&.
.sp
Deze optie is alleen beschikbaar indien het gebouwd is met ondersteuning voor libcurl\&.
.RE
.SH "GEBRUIK"
.PP
Voor elk bestand kan de gebruiker selecteren welke sporen
\fBmkvmerge\fR(1)
zou moeten nemen\&. Zij zitten allemaal in het bestand gespecificeerd met
\fB\-o\fR\&. Een lijst met bekende (en ondersteunde) bron formaten kunnen verkregen worden met de
\fB\-l\fR
optie\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBBelangrijk\fR
.ps -1
.br
.PP
De volgorde van het commando regel opties zijn belangrijk\&. Lees a\&.u\&.b\&. de sectie over:
"Optie volgorde"
als je nog onbekend bent met het programma\&.
.sp .5v
.RE
.SH "OPTIE VOLGORDE"
.PP
Voor sommige opties is de volgorde waarin zij zijn opgegeven belangrijk\&. Opties mislukken in twee categorie\(:en:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Opties die het programma be\(:invloeden en niet verbonden zijn aan enig invoerbestand\&. Deze omvatten maar zijn niet beperkt tot
\fB\-\-command\-line\-charset\fR,
\fB\-\-output\fR
of
\fB\-\-title\fR\&. Deze mogen waar dan ook op de commandoregel staan\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Opties die \('e\('en enkel invoerbestand be\(:invloedden of spoor in een invoerbestand\&. Deze opties zijn allen van toepassing op het invoerbestand op de commandoregel\&. Alle opties naar hetzelfde invoerbestand (of naar sporen in hetzelfde invoerbestand) mogen in elke volgorde geschreven worden zolang deze voor het invoerbestandsnaam staan\&. Voorbeelden die een invoerbestand be\(:invloedden zijn
\fB\-\-no\-chapters\fR
of
\fB\-\-chapter\-charset\fR\&. Voorbeelden voor een enkel spoor
\fB\-\-default\-duration\fR
of
\fB\-\-language\fR\&.
.RE
.PP
De opties worden uitgevoerd van links naar rechts\&. Indien er een optie meerdere keren is, binnen hetzelfde gebied, dan wordt de laatste gebruikt\&. Daarom zal de titel gezet worden naar "Iets anders" in het volgende voorbeeld:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o output\&.mkv \-\-title \*(AqDit \('en Dat\*(Aq input\&.avi \-\-title \*(AqIets anders\*(Aq
.fi
.if n \{\
.RE
.\}
.PP
Het volgende voorbeeld toont dat het gebruiken van de optie
\fB\-\-language\fR
tweemaal OK is, omdat zij andere gebieden gebruiken\&. Hoewel zij tot hetzelfde spoor ID behoren maar van verschillende invoer bestanden en daarom verschillende gebieden hebben:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o output\&.mkv \-\-language 0:fre fran\(,cais\&.ogg \-\-language 0:deu deutsch\&.ogg
.fi
.if n \{\
.RE
.\}
.SH "VOORBEELDEN"
.PP
Laten we aannemen dat je een bestand genoemd hebt mijn film\&.avi en het audio spoor in een ander bestand, b\&.v\&. \*(Aqmijn film\&.wav\*(Aq\&. Dan wil je eerst de audio coderen naar
OggVorbis(TM):
.sp
.if n \{\
.RS 4
.\}
.nf
$ oggenc \-q4 \-oMyMovie\&.ogg MyMovie\&.wav
.fi
.if n \{\
.RE
.\}
.PP
Na een paar minuten kan je de video en audio samenvoegen:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o mijn film\-met\-geluid\&.mkv mijn film\&.avi mijn film\&.ogg
.fi
.if n \{\
.RE
.\}
.PP
Als jouw
AVI
al een audio spoor bevat dan wordt ook die gekopieerd (als
\fBmkvmerge\fR(1)
dat audio formaat ondersteunt)\&. Om dat te voorkomen doe simpel
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o mijn film\-met\-geluid\&.mkv \-A mijn film\&.avi mijn film\&.ogg
.fi
.if n \{\
.RE
.\}
.PP
Na een paar minuten van wikken en wegen rip je een ander audio spoor, b\&.v\&. de regisseur zijn commentaar of een andere taal naar \*(Aqmijn film\-voegtoe\-geluid\&.wav\*(Aq\&. Codeer het opnieuw en voeg het samen met het andere bestand:
.sp
.if n \{\
.RS 4
.\}
.nf
$ oggenc \-q4 \-omijn film\-voegtoe\-geluid\&.ogg mijn film\-voegtoe\-geluid\&.wav
$ mkvmerge \-o MM\-complete\&.mkv mijn film\-met\-geluid\&.mkv mijn film\-voegtoe\-geluid\&.ogg 
.fi
.if n \{\
.RE
.\}
.PP
Hetzelfde resultaat kan worden verkregen met
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o MM\-complete\&.mkv \-A mijn film\&.avi mijn film\&.ogg mijn film\-voegtoe\-geluid\&.ogg
.fi
.if n \{\
.RE
.\}
.PP
Nu
mplayer(TM)
opstarten en geniet\&. Als je meerdere audio sporen hebt (of zelfs video sporen) dan kan je aangeven aan
mplayer(TM)
welk spoor af te spelen met het \*(Aq\fB\-vid\fR\*(Aq en \*(Aq\fB\-aid\fR\*(Aq opties\&. Deze zijn 0 gebaseerd en maken geen onderscheid tussen video en audio\&.
.PP
Indien het nodig is een audio spoor te synchroniseren kan je dat h\('e\('el makkelijk doen\&. Achterhaal eerst welk spoor ID het Vorbis spoor bevat
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-\-identify outofsync\&.ogg
.fi
.if n \{\
.RE
.\}
.PP
Nu kan je dat ID gebruiken voor de volgende commandoregel:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o goodsync\&.mkv \-A source\&.avi \-y 12345:200 outofsync\&.ogg
.fi
.if n \{\
.RE
.\}
.PP
Dit zou toevoegen 200ms aan stilte aan het begin van het spoor met het ID
\fB12345\fR
genomen van \*(Aqoutofsync\&.ogg\*(Aq\&.
.PP
Sommige films starten correct gesynchroniseerd maar langzaam aan verloopt dat\&. Voor dit soort films kan je een vertraag factor opgeven die worden toegevoegd aan alle tijd codes \-\- Er wordt g\('e\('en data toegevoegd of verwijderd\&. Dus, als je die factor te klein of te groot maakt dan krijg je een slecht resultaat\&. Een voorbeeld is, dat een episode die ik heb getranscodeerd met
\fB0\&.2\fR
seconden uit sync aan het eind van de film, welke
\fB77340\fR
beelden lang was\&. Bij
\fB29\&.97fps\fR
seconden ongeveer corresponderen met
\fB0\&.2\fR
seconden\&.
\fB6\fR
beelden\&. Dus ik deed
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o goodsync\&.mkv \-y 23456:0,77346/77340 outofsync\&.mkv
.fi
.if n \{\
.RE
.\}
.PP
Het resultaat was goed\&.
.PP
De sync opties kunnen ook op de zelfde manier gebruikt worden voor ondertitels\&.
.PP
Voor tekst ondertitels kan je \('e\('en van beide Windows programma\*(Aqs gebruiken (zoals
SubRipper(TM)) of het
subrip(TM)
pakket te vinden in
\fBtranscode\fR(1)\*(Aqs bronnen in de \*(Aqcontrib/subrip\*(Aq map\&. Het algemene proces is:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
pak een raw ondertiteling uit van de bron:
.sp
.if n \{\
.RS 4
.\}
.nf
$ tccat \-i /path/to/copied/dvd/ \-T 1 \-L | tcextract \-x ps1 \-t vob \-a 0x20 | subtitle2pgm \-o mymovie
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
converteer het resultaat PGM beeld/plaatje naar tekst met het \*(AqGOCR\*(Aq programma:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pgm2txt mymovie
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
spellingscontrole voor de resulterende tekst bestanden:
.sp
.if n \{\
.RS 4
.\}
.nf
$ ispell \-d american *txt
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
converteer de tekst bestanden naar een SRT bestand:
.sp
.if n \{\
.RS 4
.\}
.nf
$ srttool \-s \-w \-i mymovie\&.srtx \-o mymovie\&.srt
.fi
.if n \{\
.RE
.\}
.RE
.PP
Het resultaat bestand kan gebruikt worden als een ander invoerbestand voor
\fBmkvmerge\fR(1):
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o mymovie\&.mkv mymovie\&.avi mymovie\&.srt
.fi
.if n \{\
.RE
.\}
.PP
Als je een taal wilt opgeven voor een gegeven spoor kan dit h\('e\('el makkelijk gedaan worden\&. Zoek eerst de ISO639\-2 code voor jouw taal\&.
\fBmkvmerge\fR(1)
kan alle codes uitlijsten voor je:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-\-list\-languages
.fi
.if n \{\
.RE
.\}
.PP
Zoek in de lijst naar de taal die je nodig hebt\&. Laten we aannemen dat je twee audio sporen aan het
Matroska(TM)
bestand wilt invoegen en je hun taalcodes wilt instellen terwijl hun spoor ID\*(Aqs zijn 2 en 3\&. Dit kan gedaan worden met
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o with\-lang\-codes\&.mkv \-\-language 2:ger \-\-language 3:dut without\-lang\-codes\&.mkv
.fi
.if n \{\
.RE
.\}
.PP
Zoals je kunt zien, kan je de
\fB\-\-language\fR
schakelaar meerdere keren gebruiken\&.
.PP
Misschien zou je het ook fijn vinden dat de af speler standaard de Nederlandse taal gebruikt\&. Als je ook nog extra ondertitelingen hebt zoals b\&.v\&. Engels, Frans, en je wilt dat de af speler de Franse als standaard gebruikt\&. Kan je dit doen met
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o with\-lang\-codes\&.mkv \-\-language 2:ger \-\-language 3:dut \-\-default\-track 3 without\-lang\-codes\&.mkv \-\-language 0:eng english\&.srt \-\-default\-track 0 \-\-language 0:fre french\&.srt
.fi
.if n \{\
.RE
.\}
.PP
Als je de taal of de standaard spoor markering niet ziet, welke je had opgegeven in
\fBmkvinfo\fR(1)\*(Aqs uitvoer lees dan a\&.u\&.b\&. de sectie over:
Standaard waarden\&.
.PP
Zet de compressie uit voor een invoer bestand
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o no\-compression\&.mkv \-\-compression \-1:none MyMovie\&.avi \-\-compression \-1:none mymovie\&.srt
.fi
.if n \{\
.RE
.\}
.SH "SPOOR ID'S"
.PP
Sommige opties voor
\fBmkvmerge\fR(1)
hebben een spoor ID nodig, om aan te geven op welk spoor zij zouden moeten worden toegepast\&. Die spoor ID\*(Aqs worden getoond door de lezers bij het samenvoegen van het huidige invoer bestand, of als
\fBmkvmerge\fR(1)
is opgeroepen met de
\fB\-\-identify\fR
optie\&. Een voorbeeld van een dergelijke uitvoer:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-i v\&.mkv
File \*(Aqv\&.mkv\*(Aq: container: Matroska(TM)
Track ID 1: video (V_MS/VFW/FOURCC, DIV3)
Track ID 2: audio (A_MPEG/L3)
.fi
.if n \{\
.RE
.\}
.PP
Verwar de spoor ID\*(Aqs niet met welke zijn toegewezen aan spo(o)r(en) in het uitvoer MKV bestand met het spoor ID van het invoerbestand\&. Alleen het invoerbestand spoor ID\*(Aqs worden gebruikt voor opties die deze waarde nodig hebben\&.
.PP
Opmerking: Dat elk invoerbestand zijn eigen spoor ID\*(Aqs heeft\&. Daarom het spoor ID voor bestand \*(Aqfile1\&.ext
gerapporteerd wordt door \*(Aqmkvmerge \-\-identify\*(Aq verander niets, ongeacht hoeveel invoerbestanden in welke positie dan ook \*(Aqfile1\&.ext\*(Aq wordt gebruikt\&.
.PP
Spoor ID\*(Aqs worden toegewezen zoals dit:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

AVI
bestanden: Het video spoor heeft het ID 0\&. De audio sporen krijgen de ID\*(Aqs in oplopende volgorde beginnend bij 1\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

AAC,
AC3,
MP3,
SRT
en
WAV
bestanden: Het \*(Aqspoor\*(Aq in dat bestand krijgt het ID 0\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Meeste andere bestanden: De spoor ID\*(Aqs worden toegekend volgens de volgorde zoals het gevonden is in het bestand startend bij 0\&.
.RE
.PP
Het speciale spoor ID \*(Aq\fB\-1\fR\*(Aq is de \*(Aqjoker\*(Aq en past de bepaalde schakelaar toe op alle sporen die van een invoerbestand worden gelezen\&.
.PP
De opties die de spoor ID\*(Aqs gebruiken zijn degenen die de beschrijvingen bevatten \*(AqTID\*(Aq\&. De volgende optie gebruikt het spoor ID ook:
\fB\-\-audio\-tracks\fR,
\fB\-\-video\-tracks\fR,
\fB\-\-subtitle\-tracks\fR,
\fB\-\-button\-tracks\fR
en
\fB\-\-track\-tags\fR\&.
.SH "TEKST BESTANDEN EN KARAKTER SET CONVERSIES"
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOpmerking\fR
.ps -1
.br
.PP
Deze sectie is van toepassing op alle programma\*(Aqs in MKVToolNix zelfs wanneer all\('e\('en
\fBmkvmerge\fR(1)
genoemd wordt\&.
.sp .5v
.RE
.PP
Alle teksten in
Matroska(TM)
bestanden zijn gecodeerd in UTF\-8\&. Dit betekend, dat
\fBmkvmerge\fR(1)
alle de te lezen tekst bestanden moet converteren en evenals elke ingegeven tekst op de commandoregel om elk karakter te zetten naar UTF\-8\&. Teruggekoppeld betekend dit ook, dat
\fBmkvmerge\fR(1)\*(Aqs uitvoer terug geconverteerd moet worden naar die karakter set van UTF\-8, b\&.v\&. als een niet Engelse vertaling is gebruikt met
\fB\-\-ui\-languages\fR
of voor de originele tekst uit een
Matroska(TM)
bestand\&.
.PP

\fBmkvmerge\fR(1)
doet deze conversie automatisch gebaseerd op de aanwezigheid van een
Byte Order Marker (byte volgorde markering)
(kort:
BOM) of op basis van het huidige besturingssysteem locatie\&. Hoe het karakter van de locatie wordt \*(Aqachterhaald\*(Aq hangt af van het besturingssysteem waarop
\fBmkvmerge\fR(1)
is opgestart\&.
.PP
Tekst bestanden die starten met BOM (byte volgorde markering) zijn al gecodeerd in de vertegenwoordiging van UTF\&.
\fBmkvmerge\fR(1)
ondersteund \('e\('en van de volgende vijf modes: UTF\-8, UTF\-16 Little en Big Endian, UTF\-32 Little en Big Endian\&. Tekst bestanden met een BOM (byte volgorde markering) worden automatisch geconverteerd naar UTF\-8\&. Elke van de parameters die gezet zouden zijn voor een dergelijk bestand (b\&.v\&.
\fB\-\-sub\-charset\fR) worden stilletjes genegeerd\&.
.PP
Op Unix\-achtige systemen gebruikt
\fBmkvmerge\fR(1)
de
\fBsetlocale\fR(3)
besturingssysteem oproep, welke beurtelings de omgevingsvariabelen gebruikt
\fILANG\fR,
\fILC_ALL\fR
en
\fILC_CYPE\fR\&. Het resulterende karakter set is vaak \('e\('en van de UTF\-8 of de ISO\-8859\-* familie en wordt gebruikt voor alle tekst bestand operaties en voor het coderen van reeksen op de commandoregel voor een uitvoer naar de apparaat/houder\&.
.PP
Met Windows zijn er eigenlijk twee karakter sets welke
\fBmkvmerge\fR(1)
gebruikt, door de manier waarop het Windows commandoregel programma
\fBcmd\&.exe\fR
is ge\(:implementeerd\&. Het eerste karakter set wordt bepaald door een vraag met de
\fBGetCP()\fR
besturingssysteem oproep\&. Deze karakter set wordt standaard gebruikt voor tekst bestand conversie en voor alle elementen getoond met het
GUI
programma in het MKVToolNix pakket\&.
.PP
Een andere karakterset kan worden gebruikt als
\fBcmd\&.exe\fR
is gebruikt\&. Echter, is het lezen van de opdrachtregel gedaan met de
\fBGetCommandLineW()\fR
functie welke al een Unicode reeks retourneert\&. Daarom wordt de optie
\fB\-\-command\-line\-charset\fR
genegeerd door Windows\&. Uitvoer naar console wordt gedaan met de
\fBWriteConsoleW()\fR
functie\&. Daarom de optie
\fB\-\-output\-charset\fR
wordt alleen gebruikt in Windows als de uitvoer is geredigeerd met
\fB\-\-redirect\-output\fR\&.
.PP
Als de volgende optie aanwezig is dan is het toegestaan het karakter set te specificeren:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB\-\-sub\-charset\fR
voor tekst ondertitels en tekst ondertitel sporen opgeslagen in de houder formaat waarvan de karakter set niet onomstotelijk kan worden vastgesteld (b\&.v\&. Ogg bestanden),
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB\-\-chapter\-charset\fR
voor tekst hoofdstuk bestanden en voor hoofdstukken en bestand titels opgeslagen in de houder formaat waarvan de karakter set niet onomstotelijk kan worden vastgesteld (b\&.v\&. Ogg bestanden voor hoofdstuk informatie, spoor en bestand titels etc\&.; MP4 bestanden voor hoofdstuk informatie),
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB\-\-command\-line\-charset\fR
voor alle ingaven op de commandoregel,
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB\-\-output\-charset\fR
voor alle reeksen geschreven naar de apparaat/houder of naar een bestand wanneer de uitvoer is omgeleid met de
\fB\-\-redirect\-output\fR
optie\&.
.RE
.SH "OPTIE BESTANDEN"
.PP
Een optiebestand is een
\fBmkvmerge\fR(1)
bestand; waaruit extra commandoregel argumenten gelezen kunnen worden Dit kan worden gebruikt om bepaalde beperkingen van het dos scherm of het besturingssysteem bij het uitvoeren van externe programma\*(Aqs zoals een beperkte opdrachtregel lengte te omzeilen\&.
.PP
Er zijn verschillende regels betreffende bestand opties\&. Regels waarvan de eerste niet\-scheidingsteken een hekje is (\*(Aq#\*(Aq) worden afgehandeld als commentaar en worden genegeerd\&. Een spatie aan het eind en begin van een regel worden verwijderd\&. Elke regel mag exact \('e\('en optie bevatten\&.
.PP
Een regel die niets bevat wordt ook genegeerd\&. Een leeg argument wordt gepresenteerd via de regel \*(Aq#EMPTY#\*(Aq\&.
.PP
Verschillende karakters kunnen worden overgeslagen, b\&.v\&. als het nodig is een niet commentaar regel te starten met \*(Aq#\*(Aq\&. Deze regels worden beschreven in de sectie over:
Overslaan van speciale karakter(s) in tekst\&.
.PP
Opmerking: backslashes (\*(Aq\e\*(Aq) moeten altijd ingesloten worden\&. Hash markeringen (\*(Aq#\*(Aq) moeten ingesloten worden indien die niet starten met een commentaar\&.
.PP
De commandoregel \*(Aq\fBmkvmerge \-o "mijn bestand\&.mkv" \-A "een film\&.avi" geluid\&.ogg\fR\*(Aq kan geconverteerd worden naar het volgende optie bestand:
.sp
.if n \{\
.RS 4
.\}
.nf
# Write to the file "c:\eMatroska\emy file\&.mkv" on Windows\&.
\-o
c:\e\eMatroska\e\emy file\&.mkv
# Set the title to \*(Aq#65\*(Aq\&.
\-\-title
\eh65
# Only take the video from "a movie\&.avi"\&.
\-A
een film\&.avi
geluid\&.ogg
.fi
.if n \{\
.RE
.\}
.SH "OVERSLAAN VAN SPECIALE KARAKTER(S) IN TEKST"
.PP
Er zijn een paar plaatsen waar speciale karakters zouden of moeten worden overgeslagen\&. De regels voor het overslaan zijn simpel: elk karakter dat overgeslagen dient te worden wordt vervangen door een backslash "\e" gevolgd door een ander karakter\&.
.PP
De regels zijn: \*(Aq \*(Aq (een spatie) wordt \*(Aq\es\*(Aq, \*(Aq"\*(Aq (dubbele aanhalingstekens) wordt \*(Aq\e2\*(Aq, \*(Aq:\*(Aq wordt \*(Aq\ec\*(Aq, \*(Aq#\*(Aq wordt \*(Aq\eh\*(Aq en \*(Aq\e\*(Aq (een enkele (backslash) zelf wordt \*(Aq\e\e\*(Aq\&.
.SH "ONDERTITELINGEN"
.PP
Er zijn verschillende tekst ondertitel formaten welke kunnen worden \*(Aqingebakken\*(Aq in
Matroska(TM)\&. Tekst ondertitels moet worden her gecodeerd naar UTF\-8 zodat deze juist kunnen worden getoond door een af speler (zie de sectie over:
Tekst bestanden en karakter set conversies
voor een uitleg hoe
\fBmkvmerge\fR(1)
converteert tussen het verschillende karakter sets)\&. Kate ondertitels zijn al gecodeerd met UTF\-8 en hoeven niet gehercodeerd te worden\&.
.PP
De volgende ondertitel formaten worden momenteel ondersteund:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Ondertitel Ripper (SRT) bestand(en)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Substation Alpha (SSA) / Advanced Substation Alpha scripts (ASS)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Universeel ondertitel format (USF) bestand
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
OggKate stromen
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
VobSub bitmap ondertitel bestanden
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
PGS bitmap ondertitel bestanden zoals gevonden op BluRay schijven
.RE
.SH "BESTAND LINKEN"
.PP

Matroska(TM)
ondersteunt bestand linken welke eenvoudig zegt, dat een specifiek bestand de voorganger of de opvolger van het huidige bestand is\&. Om precies te zijn, het zijn niet echt de bestanden die gelinkt zijn maar de
Matroska(TM)
segmenten\&. En de meeste bestanden bevatten alleen \('e\('en
Matroska(TM)
segment de volgende uitleg gebruikt de term \*(Aqbestand linken\*(Aq hoewel \*(Aqsegment linken\*(Aq meer op zijn plaats zou zijn\&.
.PP
Elk segment wordt ge\(:identificeerd door een uniek 128 bit lang segment UID\&. Dit UID wordt automatisch gegenereerd door
\fBmkvmerge\fR(1)\&. Het linken wordt primair gedaan via het zetten van het segment UID\*(Aqs (kort:
SID) van het volgende/vorige bestand naar het segment kop informatie\&.
\fBmkvinfo\fR(1)
print deze
SID\*(Aqs
als het hen vindt\&.
.PP
Als een bestand wordt gesplitst in meerdere kleinere bestanden en linken wordt gebruikt, dan zullen de tijd codes niet opnieuw starten op 0 maar doorgaan op daar waar het vorige bestand eindigde\&. Op deze manier zal absolute de tijd code behouden blijven, zelfs wanneer het vorige bestand niet aanwezig/beschikbaar is (b\&.v\&. bij \*(Aqstreaming\*(Aq)\&. Als er g\('e\('en linken is gebruikt, dan zouden de tijd codes moeten starten op 0 voor elk bestand\&. Standaard gebruikt
\fBmkvmerge\fR(1)
bestand linken niet\&. Als je wilt kan je dit aanzetten met de
\fB\-\-link\fR
optie\&. Deze optie is all\('e\('en nuttig wanneer ook het splitsen actief is\&.
.PP
Ongeacht of het splitsen actief is of niet, de gebruiker kan
\fBmkvmerge\fR(1)
vertellen het geproduceerde bestand te linken naar een specifieke
SID\*(Aqs\&. Dit wordt bereikt met de opties
\fB\-\-link\-to\-previous\fR
en
\fB\-\-link\-to\-next\fR\&. Deze opties accepteren een segment
SID
in het formaat dat
\fBmkvinfo\fR(1)
uitvoert: 16 hexadecimale nummers tussen
\fB0x00\fR
en
\fB0xff\fR
voorgevoegd met \*(Aq0x\*(Aq elk, b\&.v\&. \*(Aq0x41 0xda 0x73 0x66 0xd9 0xcf 0xb2 0x1e 0xae 0x78 0xeb 0xb4 0x5e 0xca 0xb3 0x93\*(Aq\&. Als alternatief kan een kortere vorm worden gebruikt: 16 hexadecimale nummers tussen
\fB0x00\fR
en
\fB0xff\fR
zonder de \*(Aq0x\*(Aq voorvoegsel en zonder spaties, b\&.v\&. \*(Aq41da7366d9cfb21eae78ebb45ecab393\*(Aq\&.
.PP
Als splitsen wordt gebruikt, dan is het eerste bestand gelinkt naar het
SID
gegeven met
\fB\-\-link\-to\-previous\fR
en het laatste bestand is gelinkt naar
SID
gegeven met
\fB\-\-link\-to\-next\fR\&. Als splitsen niet is gebruikt, dan zal \('e\('en uitvoer bestand worden gelinkt met twee van de beide
SIDs\&.
.SH "STANDAARD WAARDEN"
.PP
De
Matroska(TM)
de specificatie verklaart dat sommige elementen een standaard waarde hebben\&. Gewoonlijk wordt een element niet naar het bestand geschreven als het niet gelijk is aan de standaard waarde, dit om ruimte te besparen\&. De elementen die gebruiker zou kunnen missen in
\fBmkvinfo\fR(1)\*(Aqs uitvoer, zijn de
\fIlanguage (taal) \fR
en de
\fI default track flag (standaard spoor markering)\fR
elementen\&. De standaard waarde voor de
\fIlanguage (taal) \fRis English (is Engels) (\*(Aqeng\*(Aq), en de standaard waarde voor de
\fIstandard track flag (standaard spoor markering)\fR
is
\fItrue (waar)\fR\&. Als je daarom gebruikt de
\fB\-\-language 0:eng\fR
voor een spoor, dan zal deze niet verschijnen in de
\fBmkvinfo\fR(1)\*(Aqs uitvoer\&.
.SH "BIJLAGEN"
.PP
Misschien wilt u ook sommige foto\*(Aqs samen met uw
Matroska(TM)
bestand houden of je gebruikt
SSA
ondertitels en je wilt een speciaal
TrueType(TM)
lettertype(n) gebruiken welke zeldzaam zijn\&. In deze gevallen kan je deze bestanden vastmaken aan het
Matroska(TM)
bestand\&. Zij zullen niet enkel bijgevoegd worden aan het bestand maar er ingevoegd worden\&. Een af speler kan deze bestanden tonen (de \*(Aqfoto\*(Aq gevallen) of hen gebruiken om de ondertitels te genereren (de \*(AqTrueType(TM)
lettertype\*(Aq gevallen)\&.
.PP
Hier is een voorbeeld hoe een foto en een
TrueType(TM)
lettertype aan het uitvoerbestand kan vast te maken:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o output\&.mkv \-A video\&.avi sound\&.ogg \e
  \-\-attachment\-description "Me and the band behind the stage in a small get\-together" \e
  \-\-attachment\-mime\-type image/jpeg \e
  \-\-attach\-file me_and_the_band\&.jpg \e
  \-\-attachment\-description "The real rare and unbelievably good looking font" \e
  \-\-attachment\-type application/octet\-stream \e
  \-\-attach\-file really_cool_font\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Als een
Matroska(TM)
bestandsbijlage bevat en is gebruikt als een invoer bestand dan zal
\fBmkvmerge\fR(1)
de bijlage kopi\(:eren naar een nieuw bestand\&. De selectie, welke bijlage wordt gekopieerd en welke niet kan veranderd worden met de opties
\fB\-\-attachments\fR
en
\fB\-\-no\-attachments\fR\&.
.SH "HOOFDSTUKKEN"
.PP
Het
Matroska(TM)
hoofdstuk systeem is krachtiger dan het oude bekende systeem van
OGM
bestanden\&. De volledige specificatie kan gevonden worden op de
\m[blue]\fBMatroska(TM)\fR\m[]\&\s-2\u[1]\d\s+2
website\&.
.PP

\fBmkvmerge\fR(1)
ondersteunt twee soorten van hoofdstuk bestanden als invoer\&. Het eerste formaat, genoemd \*(Aqsimpel hoofdstuk format\*(Aq, is hetzelfde format dat het
OGM
hulpmiddel verwacht\&. Het tweede format is een
XML
gebaseerd hoofdstuk format welke alle
Matroska(TM)\*(Aqs hoofdstuk functionaliteiten ondersteunt\&.
.SS "Een eenvoudig hoofdstuk formaat"
.PP
Dit formaat bestaat uit twee paren van regels die respectievelijk starten met \*(AqCHAPTERxx=\*(Aq en \*(AqCHAPTERxxNAME=\*(Aq\&. De eerste bevat de start tijd code en de tweede bevat de titel\&. Hier is een voorbeeld:
.sp
.if n \{\
.RS 4
.\}
.nf
CHAPTER01=00:00:00\&.000
CHAPTER01NAME=Intro
CHAPTER02=00:02:30\&.000
CHAPTER02NAME=Baby prepares to rock
CHAPTER03=00:02:42\&.300
CHAPTER03NAME=Baby rocks the house
.fi
.if n \{\
.RE
.\}
.PP

\fBmkvmerge\fR(1)
zal elk paar of regels transformeren naar \('e\('en
Matroska(TM)
ChapterAtom\&. Het plaatst geen
ChapterTrackNumber
Wat inhoudt, dat de hoofdstukken van toepassing zijn aan alle sporen in het bestand\&.
.PP
Omdat dit een tekst bestand is kan karakter set conversie nog nodig zijn\&. Zie de sectie over:
Tekst bestanden en karakter set conversies
voor een uitleg hoe
\fBmkvmerge\fR(1)
converteert tussen karakter sets\&.
.SS "Het XML gebaseerde hoofdstuk formaat"
.PP
Het
XML
gebaseerde hoofdstuk formaat lijkt op dit voorbeeld:
.sp
.if n \{\
.RS 4
.\}
.nf
<?xml version="1\&.0" encoding="ISO\-8859\-1"?>
<!DOCTYPE Chapters SYSTEM "matroskachapters\&.dtd">
<Chapters>
  <EditionEntry>
    <ChapterAtom>
      <ChapterTimeStart>00:00:30\&.000</ChapterTimeStart>
      <ChapterTimeEnd>00:01:20\&.000</ChapterTimeEnd>
      <ChapterDisplay>
        <ChapterString>A short chapter</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
      <ChapterAtom>
        <ChapterTimeStart>00:00:46\&.000</ChapterTimeStart>
        <ChapterTimeEnd>00:01:10\&.000</ChapterTimeEnd>
        <ChapterDisplay>
          <ChapterString>A part of that short chapter</ChapterString>
          <ChapterLanguage>eng</ChapterLanguage>
        </ChapterDisplay>
      </ChapterAtom>
    </ChapterAtom>
  </EditionEntry>
</Chapters>
.fi
.if n \{\
.RE
.\}
.PP
Met deze format zijn drie dingen mogelijk die niet mogelijk zijn met het simpele hoofdstuk format:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
De tijdmarkering voor het hoofdstuk eind kan ingegeven worden,
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Hoofdstukken mogen ingekapseld zijn
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
De taal en het land mogen ingesteld worden
.RE
.PP
De mkvtoolnix distributie bevat meerdere voorbeeld bestanden in de
doc
sub map welke als basis gebruikt kan worden\&.
.PP
Hieronder vindt u de ondersteunde XML\-markeringen, hun data types en, in voorkomend geval, het geldige bereik voor hun waarden:
.sp
.if n \{\
.RS 4
.\}
.nf
Chapters (master)
  EditionEntry (master)
    EditionUID (unsigned integer, valid range: 1 <= value)
    EditionFlagHidden (unsigned integer, valid range: 0 <= value <= 1)
    EditionFlagDefault (unsigned integer, valid range: 0 <= value <= 1)
    EditionFlagOrdered (unsigned integer, valid range: 0 <= value <= 1)
    ChapterAtom (master)
      ChapterAtom (master)
      ChapterUID (unsigned integer, valid range: 1 <= value)
      ChapterTimeStart (unsigned integer)
      ChapterTimeEnd (unsigned integer)
      ChapterFlagHidden (unsigned integer, valid range: 0 <= value <= 1)
      ChapterFlagEnabled (unsigned integer, valid range: 0 <= value <= 1)
      ChapterSegmentUID (binary, valid range: 1 <= length in bytes)
      ChapterSegmentEditionUID (unsigned integer, valid range: 1 <= value)
      ChapterPhysicalEquiv (unsigned integer)
      ChapterTrack (master)
        ChapterTrackNumber (unsigned integer, valid range: 1 <= value)
      ChapterDisplay (master)
        ChapterString (UTF\-8 string)
        ChapterLanguage (UTF\-8 string)
        ChapterCountry (UTF\-8 string)
      ChapterProcess (master)
        ChapterProcessCodecID (unsigned integer)
        ChapterProcessPrivate (binary)
        ChapterProcessCommand (master)
          ChapterProcessTime (unsigned integer)
          ChapterProcessData (binary)
.fi
.if n \{\
.RE
.\}
.SS "Algemene opmerkingen"
.PP
Bij het splitsen van bestanden dan zal
\fBmkvmerge\fR(1)
tevens de hoofdstukken juist bijstellen\&. Dit betekent, dat elk bestand slechts de hoofdstukingangen omvat waarop het van toepassing is, en dat de tijd codes worden gecompenseerd om te voldoen aan de nieuwe tijd codes van elk uitvoer bestand\&.
.PP

\fBmkvmerge\fR(1)
is in staat hoofdstukken te kopi\(:eren van
Matroska(TM)
bronbestanden tenzij dit expliciet is uitgezet met de
\fB\-\-no\-chapters\fR
optie\&. De hoofdstukken van alle bronnen (Matroska(TM)
bestanden, Ogg bestanden,
MP4
bestanden, hoofdstuk tekst bestanden) worden gewoonlijk niet samengevoegd maar eindigen als een gescheiden
ChapterEditions\&. Alleen wanneer de hoofdstukken worden gelezen van verschillende
Matroska(TM)
of
XML
bestanden die dezelfde editie UID\*(Aqs delen, zullen hoofdstukken samengevoegd worden tot \('e\('en
ChapterEdition\&. Als een dergelijke samenvoeging ook in andere situaties gewenst is, dan dient de gebruiker de hoofdstukken eerst te extraheren uit alle bronnen met
\fBmkvextract\fR(1), handmatig de
XML
bestanden aaneenkoppelen en nadien samenvoegen\&.
.SH "MARKERINGEN"
.SS "Introductie"
.PP

Matroska(TM)
ondersteunt een uitgebreide set markeringen welke zijn verouderd, een nieuw simpeler systeem welke worden gebruikt in de meeste overige inhoudsformaten:
\fIKEY=VALUE\fR\&. Hoewel, in
Matroska(TM)
deze markeringen ook kunnen worden ingekapseld, en beide de
\fIKEY\fR
en de
\fIVALUE\fR
zijn elementen van zichzelf\&. Het voorbeeld bestand
example\-tags\-2\&.xml
toont hoe dit nieuwe systeem te gebruiken\&.
.SS "Gebied van de markeringen"
.PP

Matroska(TM)
markeringen worden niet automatisch toegekend aan het hele bestand\&. Dat kunnen zij, maar zij kunnen ook op verschillende delen van het bestand van toepassing zijn: aan \('e\('en of meerdere sporen, aan \('e\('en of meerdere hoofdstukken, of zelfs een combinatie van beide\&.
\m[blue]\fBDe Matroska(TM) specificaties\fR\m[]\&\s-2\u[3]\d\s+2
geeft meer informatie over dit feit\&.
.PP
E\('en belangrijk feit is, dat markeringen gelinkt zijn naar sporen of hoofdstukken met de
Targets
Matroska(TM)
markeer element, en dat de gebruikte UID\*(Aqs voor dit linken
\fIniet\fR
zijn, de spoor ID\*(Aqs die overal door
\fBmkvmerge\fR(1)
gebruikt worden\&. In plaats daarvan, zijn de gebruikte UID\*(Aqs nummers welke
\fBmkvmerge\fR(1)
automatisch uitrekent (als het spoor genomen is anders dan van een
Matroska(TM)
bestandsformat) of welke zijn gekopieerd van een bronbestand, als de sporen bronbestand een
Matroska(TM)
bestand is\&. Daarom is het moeilijk te bepalen, welke UID\*(Aqs te gebruiken in het markeer bestand voordat het bestand wordt overgedragen naar
\fBmkvmerge\fR(1)\&.
.PP

\fBmkvmerge\fR(1)
kent twee opties waarmee je markeringen kunt toevoegen aan
Matroska(TM)
bestanden: De
\fB\-\-global\-tags\fR
en de
\fB\-\-tags\fR
opties\&. Het verschil is dat de vroegere optie,
\fB\-\-global\-tags\fR, de markeringen zal maken die op het volledige bestand van toepassing zijn, door te verwijderen (welke dan ook)
Targets
elementen hierboven genoemd\&. De laatstgenoemde optie,
\fB\-\-tags\fR, voegt automatisch het UID die
\fBmkvmerge\fR(1)
genereert voor de markering gespecificeerd met het
\fITID\fR
deel van de\fB\-\-tags\fR
opties\&.
.SS "Voorbeeld"
.PP
Laten we aannemen, dat je een markering wilt toevoegen aan een video spoor gelezen van een
AVI\&.
\fBmkvmerge \-\-identify file\&.avi\fR
vertelt je, dat het video spoor ID (verwar dit ID niet met het UID!) 0 is\&. Zodat het jouw markeer bestand kan cre\(:eren, laat weg alle
Targets
elementen en start
\fBmkvmerge\fR(1)
op:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \-o file\&.mkv \-\-tags 0:tags\&.xml file\&.avi
.fi
.if n \{\
.RE
.\}
.SS "Markeer bestandsformaat"
.PP

\fBmkvmerge\fR(1)
ondersteunt een
XML
gebaseerde markeer bestand format\&. Het format is rijkelijk gedocumenteerd op de
\m[blue]\fBMatroska(TM)\fR\m[]\&\s-2\u[3]\d\s+2
specificaties\&. Beide, zowel het binaire evenals de bron distributies van MKVToolNix komen met een voorbeeld bestand genaamd
example\-tags\-2\&.xml
welke simpelweg alle bekende markeringen opsomt, welke gebruikt kunnen worden als basis voor \*(Aqechte leven\*(Aq markeringsbestanden\&.
.PP
De basis is:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Het buitenste element moet zijn
<Tags>\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
E\('en logische markering welke binnenin \('e\('en paar bevindt van
<Tag>
XML
markeringen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Spaties direct voor en na een markering worden genegeerd\&.
.RE
.SS "Data typen"
.PP
Het nieuwe
Matroska(TM)
markeer systeem kent all\('e\('en twee data typen, een UTF\-8 reeks en een binair type\&. De eerste wordt gebruikt voor markeer namen en het
<String>
element terwijl het binaire type gebruikt word voor het
<Binary>
element\&.
.PP
Aangezien binaire gegevens zelf niet zouden passen in een
XML
bestand, ondersteunt
\fBmkvmerge\fR(1)
twee andere methoden om binaire data op te slaan\&. Als de inhoud van een
XML
markering start met \*(Aq@\*(Aq dan wordt de volgende tekst behandeld als een bestandsnaam\&. De corresponderende bestandsinhoud wordt gekopieerd in een
Matroska(TM)
element\&.
.PP
Anders zou de gegeven data moeten zijn een gecodeerde
Base64\&. Dit is een codering die binaire data codeert naar een gelimiteerde set van
ASCII
karakters en wordt gebruikt in b\&.v\&. email programma\*(Aqs\&.
\fBmkvextract\fR(1)
zal uitvoeren
Base64
gecodeerde data voor binaire elementen\&.
.PP
Het verouderde markeer systeem kent een paar meer data typen welke gevonden kunnen worden in de offici\(:ele
Matroska(TM)
markeer specificaties\&. Aangezien in
\fBmkvmerge\fR(1)
dit systeem niet meer wordt ondersteund, worden deze typen hier niet beschreven\&.
.SS "Bekende markeringen voor het XML bestandsformaat"
.PP
Hieronder vindt u de ondersteunde XML\-markeringen, hun data types en, in voorkomend geval, het geldige bereik voor hun waarden:
.sp
.if n \{\
.RS 4
.\}
.nf
Tags (master)
  Tag (master)
    Targets (master)
      TargetTypeValue (unsigned integer)
      TargetType (UTF\-8 string)
      TrackUID (unsigned integer)
      EditionUID (unsigned integer)
      ChapterUID (unsigned integer)
      AttachmentUID (unsigned integer)
    Simple (master)
      Simple (master)
      Name (UTF\-8 string)
      TagLanguage (UTF\-8 string)
      DefaultLanguage (unsigned integer)
      String (UTF\-8 string)
      Binary (binary)
.fi
.if n \{\
.RE
.\}
.SH "HET SEGMENT INFORMATIE XML BESTANDEN"
.PP
Met een segment informatie XML bestand is het mogelijk om bepaalde waarden in te stellen in het "segment informatie" kop veld van een
Matroska(TM)
bestand\&. Al deze waarden kunnen niet worden ingesteld via andere commando regel opties\&.
.PP
Overige "segment informatie" kopvelden kunnen gezet worden via de commandoregel opties maar niet via een XML bestand\&. Inclusief b\&.v\&. de
\fB--title\fR
en de
\fB--timecode-scale\fR
opties\&.
.PP
Er zijn nog andere elementen die kunnen worden ingesteld noch via commandoregel opties, noch via de XML\-bestanden\&. Deze bevatten de volgende elementen:
\fIDateUTC\fR
(ook bekend als "muxing date"),
\fIMuxingApp\fR,
\fIWritingApp\fR
en
\fIDuration\fR\&. Ze worden altijd gezet door
\fBmkvmerge\fR(1)
zelf\&.
.PP
Hieronder vindt u de ondersteunde XML\-markeringen, hun data types en, in voorkomend geval, het geldige bereik voor hun waarden:
.sp
.if n \{\
.RS 4
.\}
.nf
Info (master)
  SegmentUID (binary, valid range: length in bytes == 16)
  SegmentFilename (UTF\-8 string)
  PreviousSegmentUID (binary, valid range: length in bytes == 16)
  PreviousSegmentFilename (UTF\-8 string)
  NextSegmentUID (binary, valid range: length in bytes == 16)
  NextSegmentFilename (UTF\-8 string)
  SegmentFamily (binary, valid range: length in bytes == 16)
  ChapterTranslate (master)
    ChapterTranslateEditionUID (unsigned integer)
    ChapterTranslateCodec (unsigned integer)
    ChapterTranslateID (binary)
.fi
.if n \{\
.RE
.\}
.SH "MATROSKA(TM) BESTAND LAYOUT"
.PP
Het
Matroska(TM)
layout bestand is redelijk flexibel\&.
\fBmkvmerge\fR(1)
zal een bestand genereren op een vooraf gedefinieerde manier\&. Het resultaat zal er zo uitzien:
.PP
[EBML head] [segment {meta seek #1} [segment information] [track information] {attachments} {chapters} [cluster 1] {cluster 2} \&.\&.\&. {cluster n} {cues} {meta seek #2} {tags}]
.PP
De elementen in gekromde haakjes zijn optioneel en afhankelijk van de inhoud en de gebruikte opties\&. Een paar opmerkingen:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
meta zoek #1 bevat slechts een klein aantal aan niveau 1 elementen, en alleen als deze ook werkelijk bestaan: bijlagen, hoofdstukken, volg document(en) (cue), markeringen, meta zoek #2\&. Oudere versies van
\fBmkvmerge\fR(1)
zijn tevens gewend om clusters binnenin het meta zoek element te plaatsen\&. Daarom was het noodzakelijk ietwat onnauwkeurig te gokken om genoeg ruimte te reserveren\&. Het faalde vaak\&. Nu worden alleen clusters opgeslagen in het meta zoek #2, en meta zoek #1 verwijst naar het meta zoek element #2\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Bijlage, hoofdstuk en markeer elementen zijn all\('e\('en aanwezig indien zij waren toegevoegd\&.
.RE
.PP
Het kortst mogelijke
Matroska(TM)
bestand zou lijken op dit:
.PP
[EBML head] [segment [segment information] [track information] [cluster 1]]
.PP
Dit kan het geval zijn voor all\('e\('en\-audio bestanden\&.
.SH "EXTERNE TIJD CODE BESTANDEN"
.PP

\fBmkvmerge\fR(1)
staat de gebruiker toe, de tijd codes voor een specifiek spoor zelf te kiezen\&. Dit kan worden gebruikt, om bestanden met de variabele video beeld verhouding te cre\(:eren of \*(Aqgaten\*(Aq in audio te laten bevatten\&. Een beeld in dit geval, is de unit welke
\fBmkvmerge\fR(1)
afzonderlijk cre\(:eert per
Matroska(TM)
blok\&. Voor video is dit exact \('e\('en beeld, voor audio is dit \('e\('en pakket van het specifieke audio type b\&.v\&. voor
AC3
zou dit een pakket moeten zijn inhoudende
\fB1536\fR
voorbeelden\&.
.PP
Tijd code bestanden die worden gebruikt wanneer de sporen aan elkaar worden toegevoegd, moeten alleen voor het eerste deel in een reeks van sporen worden gespecificeerd\&. Bijvoorbeeld, als je twee bestanden toevoegt, v1\&.avi en v2\&.avi, en je wilt tijd codes gebruiken dan moet je commandoregel lijken op dit:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvmerge \&.\&.\&. \-\-timecodes 0:my_timecodes\&.txt v1\&.avi +v2\&.avi
.fi
.if n \{\
.RE
.\}
.PP
Er zijn vier formaten die worden herkend door
\fBmkvmerge\fR(1)\&. De eerste regel bevat altijd het versie nummer\&. Lege regels, regels alleen bevattende spaties en regels beginnend met \*(Aq#\*(Aq worden genegeerd\&.
.SS "Tijd code bestandsformaat v1"
.PP
Dit format start met de versie regel\&. De tweede regel verklaart het aantal beelden per seconde\&. Alle volgende regels bevatten drie nummers gescheiden door een komma: het start beeld (\fB0\fR
is het eerste beeld), het eind beeld en het aantal beelden binnen dit bereik\&. Het
FPS
veranderbaar nummer met een punt \*(Aq\&.\*(Aq als het decimale punt\&. De bereiken kunnen \*(Aqgaten\*(Aq bevatten waarvoor standaard
FPS
is gebruikt\&. een voorbeeld:
.sp
.if n \{\
.RS 4
.\}
.nf
# timecode format v1
assume 27\&.930
800,1000,25
1500,1700,30
.fi
.if n \{\
.RE
.\}
.SS "Tijd code bestandsformaat v2"
.PP
In dit format, bevat elke regel een tijd code voor het corresponderende beeld\&. Deze tijd code moet opgeven worden in milli seconden\&. Het mag een veranderbaar nummer zijn, maar het hoeft niet\&. Jij
\fImoet\fR
minstens zo veel tijd coderegels opgeven als er aan beelden in het spoor zijn\&. De tijd codes in dit bestand moeten gesorteerd zijn\&. Voorbeeld voor 25fps:
.sp
.if n \{\
.RS 4
.\}
.nf
# timecode format v2
0
40
80
.fi
.if n \{\
.RE
.\}
.SS "Tijd code bestandsformaat v3"
.PP
In dit format bevat elke regel een duur in seconden gevolgd door een optioneel aantal beelden per seconde\&. Beide kunnen een veranderbaar nummer zijn\&. Als het aantal beelden per seconde niet is opgegeven dan wordt het standaard aantal gebruikt\&. Voor audio, zou jij de codec zelf de tijd codes moeten laten berekenen\&. Daarvoor zou je moeten gebruiken
\fB0\&.0\fR
als het aantal beelden per seconde\&. Je kunt ook \*(Aqgaten\*(Aq cre\(:eren in de stromen door te gebruiken de \*(Aqgap\*(Aq sleutelwoord gevolgd door de duur van het \*(Aqgat\*(Aq\&. Voorbeeld voor een audio bestand:
.sp
.if n \{\
.RS 4
.\}
.nf
# timecode format v3
assume 0\&.0
25\&.325
7\&.530,38\&.236
gap, 10\&.050
2\&.000,38\&.236
.fi
.if n \{\
.RE
.\}
.SS "Tijd code bestandsformaat v4"
.PP
Dit format is identiek aan het v2 format\&. Het enige verschil is dat de tijd codes niet gesorteerd behoeven te zijn\&. Dit format zou bijna nooit gebruikt moeten worden\&.
.SH "VERLAAT CODES"
.PP

\fBmkvinfo\fR(1)
verlaat met \('e\('en van de drie afsluit codes:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB0\fR
\-\- Deze verlaat code betekend dat het samenvoegen succesvol voltooid is\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB1\fR
\-\- In dit geval heeft
\fBmkvmerge\fR(1)
ten miste \('e\('en waarschuwing uitgevaardigd, maar het samenvoegen ging door\&. Een waarschuwing gaat vooraf met de tekst \*(AqWaarschuwing:\*(Aq\&. Afhankelijk van de \*(Aqtegengekomen\*(Aq kwesties kan het resultaat goed of slecht zijn\&. De gebruiker wordt geadviseerd om zowel de waarschuwing als de resulterende bestanden te controleren\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB2\fR
\-\- Deze afsluit code wordt gebruikt nadat er een fout ontstond\&.
\fBmkvmerge\fR(1)
breekt direct af na het geven van dit waarschuw bericht\&. Fout! bereik in berichten, van een verkeerd commandoregel argument over lees/schrijf fouten naar een \*(Aqgebroken\*(Aq bestanden\&.
.RE
.SH "OMGEVINGSVARIABELEN"
.PP

\fBmkvmerge\fR(1)
gebruikt de standaard variabelen vanuit het systeem locatie (b\&.v\&.
\fILANG\fR
en de
\fILC_*\fR
family)\&. Extra variabelen:
.PP
\fIMKVTOOLNIX_DEBUG\fR en de korte versie \fIMTX_DEBUG\fR
.RS 4
De inhoud wordt behandeld alsof het via de
\fB\-\-debug\fR
optie gepasseerd is\&.
.RE
.PP
\fIMKVTOOLNIX_ENGAGE\fR en de korte versie \fIMTX_ENGAGE\fR
.RS 4
De inhoud wordt behandeld alsof het via de
\fB\-\-engage\fR
optie gepasseerd is\&.
.RE
.PP
\fIMKVTOOLNIX_OPTIONS\fR en de korte versie \fIMTX_OPTIONS\fR
.RS 4
De inhoud wordt gesplitst op een spatie\&. De gedeeltelijk resulterende reeks wordt behandeld alsof het gedaan is via de commandoregel\&. Indien het nodig is speciale karakters te gebruiken (b\&.v\&. spaties) dan moet je die "insluiten" (zie de sectie over:
Overslaan van speciale karakter(s) in tekst)\&.
.RE
.SH "ZIE OOK"
.PP

\fBmkvinfo\fR(1),
\fBmkvextract\fR(1),
\fBmkvpropedit\fR(1),
\fBmmg\fR(1)
.SH "WWW"
.PP
De laatste versie kan altijd gevonden worden op de
\m[blue]\fBMKVToolNix\fR\m[]\&\s-2\u[4]\d\s+2
thuis basis\&.
.SH "AUTEUR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Ontwikkelaar
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
Matroska(TM)
.RS 4
\%http://www.matroska.org/
.RE
.IP " 2." 4
IANA
.RS 4
\%http://www.iana.org/assignments/media-types/
.RE
.IP " 3." 4
De Matroska(TM)
specificaties
.RS 4
\%http://matroska.org/technical/specs/index.html
.RE
.IP " 4." 4
MKVToolNix
.RS 4
\%http://www.bunkus.org/videotools/mkvtoolnix/
.RE
