'\" t
.\"     Title: mkvpropedit
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 2011-09-24
.\"    Manual: Gebruiker commando\*(Aqs
.\"    Source: MkvToolNix 5.0.0
.\"  Language: Dutch
.\"
.TH "MKVPROPEDIT" "1" "2011\-09\-24" "MkvToolNix 5\&.0\&.0" "Gebruiker commando\*(Aqs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "REFERENTIENAAM"
mkvpropedit \- Modificeren van eigenschappen van een bestaande Matroska(TM) bestanden zonder een volledige samenvoeging
.SH "BEKNOPTE INHOUDSBESCHRIJVING"
.HP \w'\fBmkvpropedit\fR\ 'u
\fBmkvpropedit\fR [options] {source\-filename} {actions}
.SH "BESCHRIJVING"
.PP
Dit programma analyseert een bestaand
Matroska(TM)
bestand en kan sommige eigenschappen veranderen\&. Dan schrijft het deze veranderingen naar het bestaande bestand\&. Onder de eigenschappen die kunnen worden veranderd, zijn de segment informatie elementen (b\&.v\&. de titel) en de spoor koppen (b\&.v\&.de taal code, \*(Aqstandaard spoor\*(Aq markering of de naam)\&.
.PP
Opties:
.PP
\fB\-l\fR, \fB\-\-list\-property\-names\fR
.RS 4
Lijst alle bekende bewerkbare eigenschap namen, hun type (string, integer, boolean etc) en een korte beschrijving\&. Nadien stopt het programma\&. Daarom hoeft de parameter
\fIsource\-filename\fR
niet te worden ingegeven\&.
.RE
.PP
\fB\-p\fR, \fB\-\-parse\-mode\fR \fImode\fR
.RS 4
Stelt de ontleedt mode in\&. De parameter \*(Aq\fImode\fR\*(Aq kan zijn of \*(Aqfast\*(Aq (wat ook standaard is) of \*(Aqfull\*(Aq\&. De \*(Aqfast\*(Aq mode ontleedt niet het gehele bestand, maar gebruikt de meta zoek elementen voor lokaliseren van de benodigde elementen van een bron bestand\&. In 99% van alle gevallen is dat voldoende\&. Maar voor bestanden die geen meta zoek element bevatten of zij die beschadigd zijn, zou de gebruiker moeten opgeven de \*(Aqfull\*(Aq ontleedt mode\&. Een volledige scan kan enige minuten duren terwijl een snelle scan slechts enkele seconden duurt\&.
.RE
.PP
Akties:
.PP
\fB\-e\fR, \fB\-\-edit\fR \fIselector\fR
.RS 4
Zet de
Matroska(TM)
bestand sectie (segment informatie of bepaalde sporen koppen) die alle volgen
voeg toe,
zet
en
verwijder
acties die er op werken\&. Deze optie kan meerdere keren worden gebruikt om wijzigingen aan meer dan \('e\('en element te maken\&.
.sp
Standaard bewerkt
\fBmkvpropedit\fR(1)
de segment informatie sectie
.sp
Zie de sectie over
bewerk selecteurs/kiezer
voor een volledige beschrijving van de ingave\*(Aqs\&.
.RE
.PP
\fB\-a\fR, \fB\-\-add\fR \fIname\fR=\fIvalue\fR
.RS 4
Voegt eigenschap
\fIname\fR
toe met de waarde
\fIvalue\fR\&. De eigenschap wordt toegevoegd zelfs wanneer deze reeds bestaat\&. Opmerking: dat de meeste eigenschappen uniek zijn en niet nog een keer mogen voorkomen\&.
.RE
.PP
\fB\-s\fR, \fB\-\-set\fR \fIname\fR=\fIvalue\fR
.RS 4
Zet alle voorgekomen van de eigenschap
\fIname\fR
naar de waarde
\fIvalue\fR\&. Als een dergelijke eigenschap niet bestaat dan wordt deze toegevoegd\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR \fIname\fR
.RS 4
Verwijdert alle voorgekomen eigenschappen
\fIname\fR\&. Opmerking: sommige eigenschappen zijn vereist en kunnen niet worden verwijderd\&.
.RE
.PP
\fB\-t\fR, \fB\-\-tags\fR \fIselector\fR:\fIfilename\fR
.RS 4
Add or replace tags in the file with the ones from
filename
or remove them if
filename
is empty\&.
\fBmkvpropedit\fR(1)
reads the same XML tag format that
\fBmkvmerge\fR(1)
reads as well\&.
.sp
The
\fIselector\fR
must be one of the words
\fBall\fR,
\fBglobal\fR
or
\fBtrack\fR\&. For
\fBall\fR
\fBmkvpropedit\fR(1)
will replace or remove all tags in a file\&. With
\fBglobal\fR
only global tags will be replaced or removed\&.
.sp
With
\fBtrack\fR
\fBmkvpropedit\fR(1)
will replace tags for a specific track\&. Additionally the tags read from
filename
will be assigned to the same track\&. The track is specified in the same way
edit selectors
are specified (see below), e\&.g\&.
\-\-tags track:a1:new\-audio\-tags\&.xml\&.
.RE
.PP
\fB\-c\fR, \fB\-\-chapters\fR \fIfilename\fR
.RS 4
Add or replace chapters in the file with the ones from
filename
or remove them if
filename
is empty\&.
\fBmkvpropedit\fR(1)
reads the same XML and simple chapter formats that
\fBmkvmerge\fR(1)
reads as well\&.
.RE
.PP
Andere opties:
.PP
\fB\-\-command\-line\-charset\fR \fI(karakter\-set)\fR
.RS 4
Plaatst het karakter set om de reeksen om te zetten die vanaf de commandoregel worden opgegeven\&. Standaard wordt gebruikt de karakter set die afhankelijk is van wat er in uw besturingssysteem staat aangegeven (lokatie)\&.
.RE
.PP
\fB\-\-output\-charset\fR \fI(karakter\-set)\fR
.RS 4
Stelt de karakter set in waarnaar de reeksen dienen te worden geconverteerd naar de uitvoer\&. Standaard wordt gebruikt de karakter set die afhankelijk is van wat er in uw besturingssysteem staat aangegeven (lokatie)\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fI(bestandsnaam)\fR
.RS 4
Schrijft alle berichten naar een bestand
\fIfile\-name\fR
i\&.p\&.v naar het \*(Aqapparaat/houder\*(Aq\&. Terwijl dit gemakkelijk met uitvoer omleiden kan worden gedaan er zijn gevallen waarin deze optie nodig is: wanneer de verwerker e\&.e\&.a her\-interpreteert voordat het geschreven wordt naar het uitvoer bestand\&. De karakter set met
\fB\-\-output\-charset\fR
is toegewezen\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIcode\fR
.RS 4
Forceert de vertaling voor de te gebruiken taal
\fIcode\fR
(b\&.v\&. \*(Aqde_DE\*(Aq voor de Duitse taal)\&. Hoewel het de voorkeur heeft de \*(Aqomgevings variabelen\*(Aq te gebruiken
\fILANG\fR,
\fILC_MESSAGES\fR
en
\fILC_ALL\fR\&. Opvragen van een \*(Aqlist\*(Aq als een
\fIcode\fR
zal voor zorgen dat
\fBmkvextract\fR(1)
een lijst zal uitvoeren van alle beschikbaren vertalingen\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Wees uitgebreid en toon alle belangrijke
Matroska(TM)
elementen zoals ze zijn gelezen\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Toon gebruik informatie en sluit af\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Toon versie informatie en sluit af\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Controleert online op nieuwere versie\*(Aqs via ophalen op adres
http://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\&. Vier regels worden uitgevoerd in
key=value
stijl: het adres van waar de informatie wordt verkregen (key
version_check_url), de huidig uitgevoerde versie (key
running_version), laatst uitgebrachte versie (key
available_version
en het ophaal adres (key
download_url)\&.
.sp
Nadien sluit het programma af met een afsluitwaarde van 0 als er geen nieuwere versie beschikbaar is, met een 1 als er een nieuwere beschikbaar is en 2 indien er een fout ontstond (b\&.v\&. als de opwaardeer info niet verkregen kon worden)\&.
.sp
Deze optie is alleeen beschikbaar indien het gebouwd is met ondersteuning voor libcurl\&.
.RE
.PP
\fB@\fRoptie\*(Aqs\-bestand
.RS 4
Leest extra commandoregel argumenten in van een bestand
\fIoptions\-file\fR\&. Regels met een spatie (lege ruimte) als eerste karakter, zijn gemarkeerd als een hash (waarde) (\*(Aq#\*(Aq) worden behandeld als commentaar en genegeerd\&. Een spatie aan het begin en einde van een regel worden verwijderd\&. Elke regel mag excact \('e\('en waarde bevatten
.sp
Verschillende karakters kunnen worden overgeslagen, b\&.v\&. als het nodig is een niet commandoregel te starten met een \*(Aq#\*(Aq de regels worden beschreven in
de sectie over overslaan van tekst\&.
.sp
De commandoregel \*(Aq\fBmkvpropedit source\&.mkv \-\-edit track:a2 \-\-set name=Comments\fR\*(Aq kon niet worden geconverteerd naar het volgende optie bestand:
.sp
.if n \{\
.RS 4
.\}
.nf
# Modify source\&.mkv
source\&.mkv
# Edit the second audio track
\-\-edit
track:a2
# and set the title to \*(AqComments\*(Aq
\-\-set
title=Comments
 
.fi
.if n \{\
.RE
.\}
.RE
.SH "BEWERK SELECTEURS/KIEZERS"
.PP
De optie
\fB\-\-edit\fR
zet het
Matroska(TM)
bestand sectie (segment informatie of de bepaalde sporen knoppen) die alle volgen
voeg toe,
zet
en
verwijder
acties die er op werken\&. Dit blijft geldig todat de volgende optie
\fB\-\-edit\fR
is gevonden\&. Het argument naar deze optie wordt genoemd de bewerk selecteur/kiezer\&.
.PP
Standaard bewerkt
\fBmkvpropedit\fR(1)
de segment informatie sectie
.SS "Segment informatie"
.PP
De segment informatie kan worden geselecteerd met \('e\('en van deze drie woorden: \*(Aqinfo\*(Aq, \*(Aqsegment_info\*(Aq of \*(Aqsegmentinfo\*(Aq\&. het bevat eigenschappen zoals, segment titel of het segment
UID\&.
.SS "Spoor koppen"
.PP
Spoor koppen kunnen worden geselecteerd met een ietwat complexere selectie\&. Alle variaties starten met \*(Aqtrack:\*(Aq\&. De spoor kop eigenschappen bevatten elementen zoals de taal code, \*(Aqdefault track\*(Aq markering of het spoor naam\&.
.PP
\fBtrack:\fR\fIn\fR
.RS 4
Als de parameter
\fIn\fR
een nummer is dan zal het
\fIn\fR\*(Aqde spoor worden geselecteerd\&. De spoor volgorde is hezelfde als
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
optie uitvoert\&.
.RE
.PP
\fBtrack:\fR\fIt\fR\fIn\fR
.RS 4
Als de parameter start met \('e\('en karakter
\fIt\fR
gevolgd door een
\fIn\fR
dan zal het de
\fIn\fR\*(Aqde spoor van een specifiek spoor type geselecteerd worden\&. Het spoor type parameter
\fIt\fR
moet \('e\('en van deze vier karakters zijn: \*(Aqa\*(Aq voor een audio spoor, \*(Aqb\*(Aq voor een knop spoor, \*(Aqs\*(Aq voor een ondertitel spoor en \*(Aqv\*(Aq voor een video spoor\&. De spoor volgorde is hetzelfde wanneer
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
de optie uitvoert\&.
.RE
.PP
\fBtrack:\fR=\fIuid\fR
.RS 4
Als de parameter start met een \*(Aq=\*(Aq gevolgd door een nummer
\fIuid\fR
dan het spoor van wie het spoor
UID
element gelijk is met
\fIuid\fR\&. Spoor
UID\*(Aqs
kan verkregen worden met
\fBmkvinfo\fR(1)\&.
.RE
.PP
\fBtrack:\fR@\fInumber\fR
.RS 4
Als de parameter start met een \*(Aq@\*(Aq gevolgd door een nummer
\fInumber\fR
dan het spoor het van wie het spoornummer element gelijk is met
\fInumber\fR\&. Spoornummer kan verkregen worden met
\fBmkvinfo\fR(1)\&.
.RE
.SS "Opmerkingen"
.PP
Door de aard van de spoor bewerk selecteur/kiezer, is het mogelijk dat verschillende selecteurs/kiezers eigenlijk overeenkomen met dezelfde spoor koppen\&. In zulke gevallen, zullen alle acties voor die bewerk selecteurs/kiezers in die volgorde worden gecombineerd en uitgevoerd worden in de volgorde waarin ze zijn opgegeven op de commandoregel\&.
.SH "VOORBEELDEN"
.PP
Het volgende voorbeeld bewerkt een bestand genaamd \*(Aqfilm\&.mkv\*(Aq\&. Het zet het segment titel en modificeert de taal code van een audio en ondertitel spoor\&. Opmerking: Ddat dit voorbeeld kan worden verkort door het weglaten van de eerste optie
\fB\-\-edit\fR
omdat bewerken van het segment informatie element in elk geval standaard is voor alle opties welke worden gevonden voor de eerste
\fB\-\-edit\fR
optie\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit film\&.mkv \-\-edit info \-\-set "title=De film" \-\-edit track:a1 \-\-set language=dut \-\-edit track:a2 \-\-set language=eng
 
.fi
.if n \{\
.RE
.\}
.PP
Het tweede voorbeeld, verwijdert de \*(Aqstandaard spoor markering\*(Aq van het eerste ondertitel spoor en plaatst het voor de tweede\&. Opmerking: Dat
\fBmkvpropedit\fR(1), integenstelling tot
\fBmkvmerge\fR(1), niet instelt de \*(Aqstandaard spoor markering\*(Aq van andere sporen naar \*(Aq0\*(Aq als het automatisch is ingesteld op \*(Aq1\*(Aq voor een verschillend spoor\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit film\&.mkv \-\-edit track:s1 \-\-set flag\-default=0 \-\-edit track:s2 \-\-set flag\-default=1
 
.fi
.if n \{\
.RE
.\}
.PP
Replacing the tags for the second subtitle track in a file looks like this:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit movie\&.mkv \-\-tags track:s2:new\-subtitle\-tags\&.xml
  
.fi
.if n \{\
.RE
.\}
.PP
Removing all tags requires leaving out the file name:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit movie\&.mkv \-\-tags all:
  
.fi
.if n \{\
.RE
.\}
.PP
Replacing the chapters in a file looks like this:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit movie\&.mkv \-\-chapters new\-chapters\&.xml
  
.fi
.if n \{\
.RE
.\}
.PP
Removing all chapters requires leaving out the file name:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit movie\&.mkv \-\-chapters \*(Aq\*(Aq
  
.fi
.if n \{\
.RE
.\}
.SH "VERLAAT CODES"
.PP

\fBmkvpropedit\fR(1)
verlaat met \('e\('en van drie verlaat codes:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB0\fR
\-\- Deze verlaat code betekend dat het modificeren succesvol voltooid is\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB1\fR
\-\- In dit geval heeft
\fBmkvpropedit\fR(1)
minstends \('e\('en waarschuwing uitgegeven, maar extractie is doorgegaan\&. Een waarschuwing wordt vooraf bepaald met de tekst \*(AqWarning:\*(Aq\&. Afhankelijk van de \*(Aqtegengekomen\*(Aq kwesties kan het resltaat goed of slecht zijn\&. De gebruiker wordt geadviseerd, om zowel de waarschuwing als de resulterende bestanden te controleren\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB2\fR
\-\- Deze afsluit code wordt gebruikt nadat er een fout ontstond\&.
\fBmkvpropedit\fR(1)
breekt direct af na het geven van dit waarschuw bericht\&. Fout berichten, bereik van een verkeerd commandoregel argument over lees/schrijf fouten naar een \*(Aqgebroken\*(Aq bestanden\&.
.RE
.SH "OVERSLAAN VAN SPECIALE KARAKTER(S) IN TEKST"
.PP
Er zijn een paar plaatsen waar speciale karakters zouden of moeten worden overgeslagen\&. De regels voor het overslaan zijn simpel: elk karakter dat overgeslagen dient te worden wordt vervangen door een backslash "\e" gevolgd door een ander karakter\&.
.PP
De regels zijn: \*(Aq \*(Aq wordt \*(Aq\es\*(Aq, \*(Aq"\*(Aq wordt \*(Aq\e2\*(Aq, \*(Aq:\*(Aq wordt \*(Aq\ec\*(Aq, \*(Aq#\*(Aq wordt \*(Aq\eh\*(Aq en \*(Aq\e\*(Aq zelf wordt \*(Aq\e\e\*(Aq\&.
.SH "ZIE OOK"
.PP

\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvextract\fR(1),
\fBmmg\fR(1)
.SH "WWW"
.PP
De laatste versie kan altijd gevonden worden op de
\m[blue]\fBMKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2
thuis basis\&.
.SH "AUTEUR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Ontwikkelaar
.RE
.SH "NOTEN"
.IP " 1." 4
MKVToolNix
.RS 4
\%http://www.bunkus.org/videotools/mkvtoolnix/
.RE
